import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

describe("chat history flow", () => {
  const chatViewSource = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")
  const chatHtmlSource = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")
  const chatStreamSource = readFileSync(join(import.meta.dir, "..", "src", "chat-stream.ts"), "utf8")

  test("posts sessions and loading state to the webview", () => {
    expect(chatViewSource).toContain("sessions: this.sessions")
    expect(chatViewSource).toContain("currentSessionID: this.sessionID")
    expect(chatViewSource).toContain("loadingMessages: this.loadingMessages")
  })

  test("loads messages when a session is selected", () => {
    expect(chatViewSource).toContain('{ type: "selectSession"; sessionID: string }')
    expect(chatViewSource).toContain("private async selectSession")
    expect(chatViewSource).toContain("await this.loadSessionMessages(client, sessionID)")
    expect(chatViewSource).toContain("client.getMessages(sessionID, SESSION_MESSAGE_LIMIT, signal)")
  })

  test("refreshes session history after session-changing actions", () => {
    expect(chatViewSource).toContain("private async refreshSessionList")
    expect(chatViewSource).toContain("await this.refreshSessionList(client)")
    expect(chatViewSource).toContain("client.listSessions(signal)")
    expect(chatViewSource).toContain("this.isVisibleChatSession(session)")
    expect(chatViewSource).toContain("isPluginChatSession(session)")
  })

  test("hides inline completion sessions from chat history", () => {
    expect(chatViewSource).toContain("isInlineCompletionSession")
    expect(chatViewSource).toContain("hiddenCompletionSessions")
    expect(chatViewSource).toContain("if (isInlineCompletionSession(session)) return false")
  })

  test("hides persisted inline completion prompts when old sessions are selected", () => {
    expect(chatViewSource).toContain("messages.some(isInlineCompletionMessage)")
    expect(chatViewSource).toContain("private async hideCompletionSession")
    expect(chatViewSource).toContain("this.sessions = this.sessions.filter((session) => session.id !== sessionID)")
    expect(chatViewSource).toContain("this.reconcileSessionSelection()")
  })

  test("hides external OpenCode sessions from plugin chat history", () => {
    expect(chatViewSource).toContain("CHAT_SESSION_TITLE")
    expect(chatViewSource).toContain("hiddenExternalSessions")
    expect(chatViewSource).toContain("messages.some(isExternalChatMessage)")
    expect(chatViewSource).toContain("private async hideExternalSession")
    expect(chatViewSource).toContain("Hidden external OpenCode session")
  })

  test("recovers when the remote server has lost the selected session", () => {
    expect(chatViewSource).toContain("isSessionNotFoundError")
    expect(chatViewSource).toContain("private reconcileSessionSelection")
    expect(chatViewSource).toContain("this.sessions.some((session) => session.id === this.sessionID)")
    expect(chatViewSource).toContain("private async loadSelectedSessionMessages")
    expect(chatViewSource).toContain("private async recoverMissingSession")
  })

  test("retries sends with a new session after stale-session errors", () => {
    expect(chatViewSource).toContain("let preparedMessage")
    expect(chatViewSource).toContain("private async sendPreparedMessage")
    expect(chatViewSource).toContain("Selected remote session was not found; retrying with a new session.")
    expect(chatViewSource).toContain("this.clearMissingSession(this.sessionID)")
  })

  test("waits for local code graph readiness before sending", () => {
    expect(chatViewSource).toContain("codeGraph: this.deps.codeGraph")
    expect(chatViewSource).toContain("private async waitForCodeGraphReady")
    expect(chatViewSource).toContain("await this.waitForCodeGraphReady(settings)")
    expect(chatViewSource).toContain("this.deps.codeGraph.waitForReady()")
    expect(chatViewSource).toContain("CodeGraphReadinessError")
    expect(chatViewSource).toContain("codeGraphWaitDetail")
    expect(chatViewSource).toContain("[codegraph] blocked send")
  })

  test("streams chat replies through OpenCode events with blocking fallback", () => {
    expect(chatViewSource).toContain("ensureEventSubscription")
    expect(chatViewSource).toContain("subscribeEvents")
    expect(chatViewSource).toContain("sendMessageAsync")
    expect(chatViewSource).toContain("client.sendMessage({")
    expect(chatViewSource).toContain("finishStreamingSession")
    expect(chatStreamSource).toContain('case "message.part.updated"')
    expect(chatStreamSource).toContain('case "session.status"')
  })

  test("recovers the composer from remote retry session statuses", () => {
    expect(chatViewSource).toContain("SEND_STATUS_POLL_INTERVAL_MS")
    expect(chatViewSource).toContain("client.getSessionStatuses(signal)")
    expect(chatViewSource).toContain("startSendStatusWatchdog")
    expect(chatViewSource).toContain("failActiveSendWithRetry")
    expect(chatViewSource).toContain('status?.type === "retry"')
    expect(chatViewSource).toContain("result.retry")
    expect(chatViewSource).toContain("remoteRetryMessage")
    expect(chatViewSource).toContain("this.clearActiveSendState()")
    expect(chatViewSource).toContain("this.sending = false")
    expect(chatViewSource).toContain("远端 OpenCode 正在重试模型请求")
    expect(chatStreamSource).toContain("retry?: OpenCodeSessionStatus")
    expect(chatStreamSource).toContain('retry: type === "retry" ? normalizedStatus : undefined')
  })

  test("renders markdown, code copy, and thinking state in the webview", () => {
    expect(chatHtmlSource).toContain("function renderMarkdownInto")
    expect(chatHtmlSource).toContain("function renderTextMarkdown")
    expect(chatHtmlSource).toContain("mdQuote")
    expect(chatHtmlSource).toContain("mdDivider")
    expect(chatHtmlSource).toContain('const tag = ordered ? "ol" : "ul"')
    expect(chatHtmlSource).toContain("document.createElement(tag)")
    expect(chatHtmlSource).toContain("function appendInlineMarkdown")
    expect(chatHtmlSource).toContain("mdStrong")
    expect(chatHtmlSource).toContain("mdEm")
    expect(chatHtmlSource).toContain("function detectTableBlock")
    expect(chatHtmlSource).toContain("function detectMarkdownTable")
    expect(chatHtmlSource).toContain("function detectDelimitedTable")
    expect(chatHtmlSource).toContain("function detectPlainAlignedTable")
    expect(chatHtmlSource).toContain("function detectKeyValueBlock")
    expect(chatHtmlSource).toContain("looksLikeMarkdownListRows")
    expect(chatHtmlSource).toContain("isMarkdownListMarkerCell")
    expect(chatHtmlSource).toContain("looksLikeMarkdownLabelRows")
    expect(chatHtmlSource).toContain("isMarkdownLabelCellSafe")
    expect(chatHtmlSource).toContain("String.fromCharCode(0xff1a)")
    expect(chatHtmlSource).toContain("function tableBlock")
    expect(chatHtmlSource).toContain("tableToolbar")
    expect(chatHtmlSource).toContain("tableScroll")
    expect(chatHtmlSource).toContain("copyTableMarkdown")
    expect(chatHtmlSource).toContain("copyTableCsv")
    expect(chatHtmlSource).toContain("toggleTableRaw")
    expect(chatHtmlSource).toContain("function tableToMarkdown")
    expect(chatHtmlSource).toContain("function tableToCsv")
    expect(chatHtmlSource).toContain("Raw table text")
    expect(chatHtmlSource).toContain("function codeBlock")
    expect(chatHtmlSource).toContain("codeLanguage")
    expect(chatHtmlSource).toContain("appendHighlightedCode")
    expect(chatHtmlSource).toContain("tokenizeCode")
    expect(chatHtmlSource).toContain("normalizeCodeLanguage")
    expect(chatHtmlSource).toContain("syntaxKeyword")
    expect(chatHtmlSource).toContain("syntaxString")
    expect(chatHtmlSource).toContain("syntaxComment")
    expect(chatHtmlSource).toContain("syntaxFunction")
    expect(chatHtmlSource).toContain("syntaxInserted")
    expect(chatHtmlSource).toContain("async function copyCode")
    expect(chatHtmlSource).toContain('button.textContent = "Copied"')
    expect(chatHtmlSource).toContain("function thinkingNode")
    expect(chatHtmlSource).toContain("hasAssistantContentAfterLastUser")
  })

  test("renders message actions, outline, and large-answer controls", () => {
    expect(chatHtmlSource).toContain("function messageActions")
    expect(chatHtmlSource).toContain("copyAnswer")
    expect(chatHtmlSource).toContain("copyMarkdown")
    expect(chatHtmlSource).toContain("collapseMessage")
    expect(chatHtmlSource).toContain("jumpStructure")
    expect(chatHtmlSource).toContain("function toggleMessageCollapse")
    expect(chatHtmlSource).toContain("function toggleLongMessage")
    expect(chatHtmlSource).toContain("function messageOutline")
    expect(chatHtmlSource).toContain("messageOutlineSummary")
    expect(chatHtmlSource).toContain("messageLongHint")
    expect(chatHtmlSource).toContain("longAnswer")
    expect(chatHtmlSource).toContain("longExpanded")
    expect(chatHtmlSource).toContain("function scrollToNextMessageStructure")
    expect(chatHtmlSource).toContain("function markdownToPlainText")
    expect(chatHtmlSource).toContain('aria-expanded", options.isCollapsed ? "false" : "true"')
    expect(chatHtmlSource).toContain("function onPopupMenuKeydown")
    expect(chatHtmlSource).toContain("function focusPopupMenuItem")
    expect(chatHtmlSource).toContain('event.key === "ArrowDown"')
    expect(chatHtmlSource).toContain('event.key === "ArrowUp"')
    expect(chatHtmlSource).toContain("forced-colors: active")
    expect(chatHtmlSource).toContain('event.key !== "Escape"')
  })

  test("collapses the composer and context panel", () => {
    expect(chatHtmlSource).toContain('id="composerStatusBar"')
    expect(chatHtmlSource).toContain('id="composerStatusToggle"')
    expect(chatHtmlSource).toContain('id="panelStatusPill"')
    expect(chatHtmlSource).toContain('id="contextStatusPill"')
    expect(chatHtmlSource).toContain('id="indexStatusPill"')
    expect(chatHtmlSource).toContain('id="guardStatusPill"')
    expect(chatHtmlSource).toContain('id="usageStatusPill"')
    expect(chatHtmlSource).toContain('aria-controls="composerPanel"')
    expect(chatHtmlSource).toContain("composerToggleIcon")
    expect(chatHtmlSource).toContain("composerToggleFull")
    expect(chatHtmlSource).toContain("composerToggleShort")
    expect(chatHtmlSource).toContain("Hide input")
    expect(chatHtmlSource).toContain("Show input")
    expect(chatHtmlSource).toContain('el("send").textContent = state.sending ? "..." : "Send"')
    expect(chatHtmlSource).toContain("let composerCollapsed = false")
    expect(chatHtmlSource).toContain('let composerPinnedStatusPopover = ""')
    expect(chatHtmlSource).toContain('let composerHoverStatusPopover = ""')
    expect(chatHtmlSource).toContain("let composerHoverCloseTimer = 0")
    expect(chatHtmlSource).toContain("function toggleComposerPanel")
    expect(chatHtmlSource).toContain("function closeComposerPopups")
    expect(chatHtmlSource).toContain("function renderComposerStatusBar")
    expect(chatHtmlSource).toContain("function bindComposerStatusPill")
    expect(chatHtmlSource).toContain("function showComposerHoverPopover")
    expect(chatHtmlSource).toContain("function activeComposerStatusPopover")
    expect(chatHtmlSource).toContain("function toggleComposerStatusPopover")
    expect(chatHtmlSource).toContain("function renderComposerStatusPopover")
    expect(chatHtmlSource).toContain("panel.hidden = composerCollapsed")
    expect(chatHtmlSource).toContain("composerWrap.collapsed")
    expect(chatHtmlSource).toContain("Ctx ")
    expect(chatHtmlSource).toContain("Guard warning")
    expect(chatHtmlSource).toContain("compactRing")
    expect(chatHtmlSource).toContain("statusRing")
    expect(chatHtmlSource).toContain("function formatRingProgress")
    expect(chatHtmlSource).toContain("function indexStatusRing")
    expect(chatHtmlSource).toContain("function contextUsageRatio")
    expect(chatHtmlSource).toContain("composerStatusPill context")
    expect(chatHtmlSource).toContain("composerStatusPill index")
    expect(chatHtmlSource).toContain("composerStatusPill guard ok")
    expect(chatHtmlSource).toContain("composerStatusPill usage pending")
    expect(chatHtmlSource).toContain("statusPopoverActions")
    expect(chatHtmlSource).toContain("contextRemoveButton")
    expect(chatHtmlSource).not.toContain('id="guard"')
    expect(chatHtmlSource).not.toContain('id="usageMeter"')
    expect(chatHtmlSource).not.toContain('id="codeGraph"')
    expect(chatHtmlSource).not.toContain('id="chips"')
  })

  test("supports markdown export from explicit UI and model-classified prompts", () => {
    expect(chatHtmlSource).toContain('id="exportMarkdown"')
    expect(chatHtmlSource).toContain('class="composerActionRow"')
    expect(chatHtmlSource).toContain('class="secondary exportButton composerIconButton"')
    expect(chatHtmlSource).toContain('aria-label="Export current chat to Markdown"')
    expect(chatHtmlSource).toContain('class="srOnly"')
    expect(chatHtmlSource).toContain("border: 0;")
    expect(chatHtmlSource).not.toContain("composerIconActions")
    expect(chatHtmlSource).toContain('type: "exportMarkdown", scope: "session"')
    expect(chatHtmlSource).toContain('event.data.type === "exportStatus"')
    expect(chatHtmlSource).toContain("looksLikeExportRequest")
    expect(chatViewSource).toContain('type: "exportMarkdown"')
    expect(chatViewSource).toContain("private async handleSendMessage")
    expect(chatViewSource).toContain("parseExplicitExportCommand(text)")
    expect(chatViewSource).toContain("isExportIntentCandidate(text)")
    expect(chatViewSource).toContain("buildExportIntentPrompt")
    expect(chatViewSource).toContain("parseExportIntentResponse(messageText(response))")
    expect(chatViewSource).toContain("private async exportMarkdown")
    expect(chatViewSource).toContain("formatChatExportMarkdown")
    expect(chatViewSource).toContain("showSaveDialog")
    expect(chatViewSource).toContain("workspace.fs.writeFile")
    expect(chatViewSource).toContain("EXPORT_INTENT_SESSION_TITLE")
    expect(chatViewSource).toContain("hiddenExportIntentSessions")
  })

  test("collapses reasoning content into a details card", () => {
    expect(chatViewSource).toContain("splitThinkingFromParts(message.parts)")
    expect(chatViewSource).toContain('type: "reasoning"')
    expect(chatViewSource).toContain('title: "Thinking"')
    expect(chatHtmlSource).toContain('part.type !== "reasoning"')
    expect(chatHtmlSource).toContain('part.type === "reasoning" ? " reasoning" : ""')
  })

  test("marks remote server filesystem tool usage", () => {
    expect(chatViewSource).toContain("SERVER_FILESYSTEM_TOOLS")
    expect(chatViewSource).toContain("serverToolWarning")
    expect(chatViewSource).toContain("flaggedSessions")
    expect(chatHtmlSource).toContain("Server tools used")
  })
})
