import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { createChatViewHtml, createNonce } from "../src/chat-html"

describe("chat webview html", () => {
  test("creates CSP-safe alphanumeric nonces", () => {
    for (let index = 0; index < 20; index++) {
      expect(createNonce()).toMatch(/^[A-Za-z0-9]{32}$/)
    }
  })

  test("uses the same nonce in CSP and script tag", () => {
    const html = createChatViewHtml("vscode-resource:", "AbC123")

    expect(html).toContain("script-src 'nonce-AbC123'")
    expect(html).toContain('<script nonce="AbC123">')
  })

  test("contains the webview script smoke-test markers", () => {
    const html = createChatViewHtml("vscode-resource:", "Smoke123")

    expect(html).toContain("acquireVsCodeApi()")
    expect(html).toContain('class="topbar"')
    expect(html).toContain('id="historyToggle"')
    expect(html).toContain('id="sessionList"')
    expect(html).toContain('id="messages"')
    expect(html).toContain("timelineItem")
    expect(html).toContain('class="composer"')
    expect(html).toContain('class="composerToolbar"')
    expect(html).toContain('id="composerHint"')
    expect(html).toContain('id="suggestions"')
    expect(html).toContain('id="send"')
    expect(html).toContain('id="guard"')
    expect(html).toContain('id="usageMeter"')
    expect(html).toContain("renderUsageMeter")
    expect(html).toContain("Usage pending")
    expect(html).toContain("messageUsage")
    expect(html).toContain("historyError")
    expect(html).toContain('id="codeGraph"')
    expect(html).toContain("renderCodeGraph")
    expect(html).toContain("Code graph disabled")
    expect(html).toContain("Waiting for code graph indexing")
    expect(html).toContain("Indexed: ")
    expect(html).toContain("Indexing...")
    expect(html).toContain("Code graph stale")
    expect(html).toContain("Code graph error")
    expect(html).toContain('data-code-graph-action')
    expect(html).toContain('message: "indexCodeGraph"')
    expect(html).toContain('message: "rebuildCodeGraph"')
    expect(html).toContain('message: "showCodeGraphStatus"')
    expect(html).toContain('id="modelSelect"')
    expect(html).toContain('id="modelTrigger"')
    expect(html).toContain('id="modelMenu"')
    expect(html).toContain('id="refreshModels"')
    expect(html).toContain('id="manualModel"')
    expect(html).toContain('el("attach").addEventListener("click"')
    expect(html).toContain('el("connect").addEventListener("click"')
    expect(html).toContain('el("test").addEventListener("click"')
    expect(html).toContain('let pendingAction = ""')
    expect(html).toContain('pendingAction = type === "testWithSettings" ? "test" : "connect"')
    expect(html).toContain('type: "selectSession"')
    expect(html).toContain('type: "refreshSessions"')
    expect(html).toContain('type: "searchFilesForMention"')
    expect(html).toContain("onCodeGraphAction")
    expect(html).toContain("renderMarkdownInto")
    expect(html).toContain("copyCode")
    expect(html).toContain("thinking")
    expect(html).toContain("prefers-reduced-motion")
    expect(html).toContain("history-closed history-narrow")
    expect(html).toContain("history-wide")
    expect(html).toContain("flex: 0 0 auto")
    expect(html).toContain("No current file captured")
    expect(html).toContain("autoContext")
    expect(html).toContain("Current: ")
    expect(html).toContain("mentionedFiles")
    expect(html).toContain("Local-only guard active")
    expect(html).toContain("guardSummary")
    expect(html).toContain("guardDetail")
    expect(html).toContain("VS Code agent: ")
    expect(html).toContain('id="agentTrigger"')
    expect(html).toContain('id="agentMenu"')
    expect(html).toContain("localOnlyAgentBlocked")
    expect(html).toContain("agentMatchesRequired")
    expect(html).toContain("canonicalAgentName")
    expect(html).toContain("Required VS Code local agent is unavailable")
    expect(html).toContain("Unavailable for VS Code local mode")
    expect(html).toContain("button.disabled = Boolean(disabled)")
    expect(html).toContain(".modelMenuItem.disabled")
    expect(html).toContain("Model: server default")
    expect(html).toContain("requestId")
    expect(html).toContain("Searching workspace files")
    expect(html).toContain("No files found")
    expect(html).toContain("Index truncated")
    expect(html).toContain("server filesystem tool used")
    expect(html).toContain('vscode.postMessage({ type: "ready" })')
    expect(html).toContain("OpenCode Remote UI loading")
  })

  test("does not auto-refresh when the webview resolves", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")
    const start = source.indexOf("resolveWebviewView")
    const end = source.indexOf("setConnectionState", start)
    const resolveBody = source.slice(start, end)

    expect(resolveBody).not.toContain("refresh()")
    expect(resolveBody).toContain("postState()")
  })

  test("chat provider handles code graph webview actions", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")

    expect(source).toContain('{ type: "indexCodeGraph" }')
    expect(source).toContain('{ type: "rebuildCodeGraph" }')
    expect(source).toContain('{ type: "showCodeGraphStatus" }')
    expect(source).toContain('case "indexCodeGraph"')
    expect(source).toContain('case "rebuildCodeGraph"')
    expect(source).toContain('case "showCodeGraphStatus"')
    expect(source).toContain("indexWorkspace(force)")
    expect(source).toContain("showStatus()")
  })
})
