import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { createChatViewHtml, createNonce } from "../src/chat-html"

describe("chat webview html", () => {
  test("creates CSP-safe alphanumeric nonces", () => {
    for (let index = 0; index < 20; index++) {
      expect(createNonce()).toMatch(/^[A-Za-z0-9]{32}$/)
    }
  })

  test("uses the same nonce in CSP and script tag", () => {
    const html = createChatViewHtml("vscode-resource:", "AbC123")

    expect(html).toContain("img-src vscode-resource: data:")
    expect(html).toContain("script-src 'nonce-AbC123'")
    expect(html).toContain('<script nonce="AbC123">')
  })

  test("loads Mermaid from a local webview resource with strict rendering", () => {
    const html = createChatViewHtml(
      "vscode-resource:",
      "Mermaid123",
      "",
      "vscode-resource://media/vendor/mermaid/mermaid.min.js?x=1&y=2",
    )

    expect(html).toContain("script-src 'nonce-Mermaid123' vscode-resource:")
    expect(html).toContain('<script nonce="Mermaid123" src="vscode-resource://media/vendor/mermaid/mermaid.min.js?x=1&amp;y=2"></script>')
    expect(html).toContain("MERMAID_MAX_SOURCE_BYTES")
    expect(html).toContain("mermaid.initialize({")
    expect(html).toContain("startOnLoad: false")
    expect(html).toContain('securityLevel: "strict"')
    expect(html).toContain("htmlLabels: false")
    expect(html).not.toContain("bindFunctions")
  })

  test("renders Mermaid fences as diagram blocks with source fallback", () => {
    const html = createChatViewHtml("vscode-resource:", "Diagram123", "", "vscode-resource://media/vendor/mermaid/mermaid.min.js")

    expect(html).toContain("function isMermaidLanguage")
    expect(html).toContain('return value === "mermaid" || value === "mmd";')
    expect(html).toContain("function diagramBlock(language, codeText)")
    expect(html).toContain('block.className = "diagramBlock";')
    expect(html).toContain('block.setAttribute("data-diagram-kind", "mermaid");')
    expect(html).toContain('source.className = "toggleDiagramSource oc-icon-btn oc-liquid-btn";')
    expect(html).toContain('setIconOnlyButton(source, "references", "Show Mermaid source");')
    expect(html).toContain('setIconOnlyButton(copy, "copy", "Copy Mermaid source");')
    expect(html).toContain("function renderMermaidFallback")
    expect(html).toContain('"Mermaid render failed: " + diagramErrorMessage(error)')
    expect(html).toContain("function pendingMermaidSourceBlock")
    expect(html).toContain("if (inCode) flushPendingCode();")
  })

  test("renders the media brand icon instead of CM text for ChipMate avatars", () => {
    const html = createChatViewHtml("vscode-resource:", "Brand123", "vscode-resource://media/chipmate-icon.png?x=1&y=2")

    expect(html).toContain('class="mark brandMark"')
    expect(html).toContain('class="brandIconImage"')
    expect(html).toContain('src="vscode-resource://media/chipmate-icon.png?x=1&amp;y=2"')
    expect(html).toContain('const BRAND_ICON_URI = "vscode-resource://media/chipmate-icon.png?x=1&y=2";')
    expect(html).toContain("function setAvatarContent")
    expect(html).toContain("function appendBrandAvatar")
    expect(html).toContain('root.classList.add("brandAvatar");')
    expect(html).not.toContain('<div class="mark">CM</div>')
    expect(html).not.toContain('avatar.textContent = "CM";')
  })

  test("emits syntactically valid webview script", () => {
    const html = createChatViewHtml("vscode-resource:", "Syntax123")
    const scriptMatch = html.match(/<script[^>]*>([\s\S]*)<\/script>/)
    if (!scriptMatch) throw new Error("Expected generated webview HTML to contain a script tag.")

    expect(() => new Function("acquireVsCodeApi", scriptMatch[1])).not.toThrow()
  })

  test("renders the local VS Code native plus icon system", () => {
    const html = createChatViewHtml("vscode-resource:", "Native123")
    const iconSource = readFileSync(join(import.meta.dir, "..", "src", "webview", "liquid-icons.ts"), "utf8")

    expect(html).toContain("LIQUID_ICONS")
    expect(html).toContain('class="oc-liquid-icon"')
    expect(html).toContain('class="oc-liquid-icon-disabled-slash"')
    expect(html).toContain('viewBox="0 0 24 24"')
    expect(html).toContain('stroke="currentColor"')
    expect(iconSource).toContain('| "tool"')
    expect(iconSource).toContain('| "toolDisabled"')
    expect(iconSource).toContain('| "completion"')
    expect(iconSource).toContain('| "close"')
    expect(iconSource).toContain('| "panelBottomClose"')
    expect(iconSource).toContain('| "panelBottomOpen"')
    expect(iconSource).toContain("toolDisabled: [")
    expect(iconSource).toContain("completion: [")
    expect(iconSource).toContain("M4.8 4c3.3 0 4.7 1.5 4.7 4.3")
    expect(iconSource).toContain("M10.5 4c3.3 0 4.7 1.5 4.7 4.3")
    expect(iconSource).toContain("close: [")
    expect(iconSource).toContain("panelBottomClose: [")
    expect(iconSource).toContain("panelBottomOpen: [")
    expect(iconSource).toContain('d: "M5 5 19 19"')
    expect(iconSource).not.toContain('d: "M5 19 19 5"')
    expect(iconSource).toContain('className: "oc-liquid-icon-disabled-slash"')
    expect(html).toContain(".oc-tool-btn")
    expect(html).toContain(".oc-icon-btn")
    expect(html).toContain(".oc-icon-toggle")
    expect(html).toContain(".oc-chip")
    expect(html).toContain(".oc-badge")
    expect(html).toContain(".oc-primary-btn")
    expect(html).toContain(".oc-settings-tile")
    expect(html).toContain(".oc-liquid-btn")
    expect(html).toContain(".oc-liquid-toggle")
    expect(html).toContain(".oc-liquid-chip")
    expect(html).toContain(".oc-liquid-card")
    expect(html).toContain(".oc-liquid-actionbar")
    expect(html).toContain(".oc-liquid-badge")
    expect(html).toContain(".oc-status-dot")
    expect(html).not.toContain("backdrop-filter")
    expect(html).not.toContain("--oc-glass")
    expect(html).not.toContain("lucideIcons")
    expect(html).not.toContain("topbarIcon(")
    expect(html).not.toContain("composerIcon(")
  })

  test("uses quiet native controls for header, composer, empty state, settings, and RAG", () => {
    const html = createChatViewHtml("vscode-resource:", "Controls123")
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    expect(html).toContain('id="historyToggle" class="oc-icon-btn oc-liquid-btn headerHistoryAction" type="button" title="History" aria-label="History"')
    expect(html).toContain('id="newSession" class="oc-icon-btn oc-liquid-btn" type="button" title="New session" aria-label="New session"')
    expect(html).toContain('id="syncState" class="oc-icon-btn oc-liquid-btn" type="button" title="Refresh chat state" aria-label="Refresh chat state"')
    expect(source).toContain('id="syncState" class="oc-icon-btn oc-liquid-btn" type="button" title="Refresh chat state" aria-label="Refresh chat state">${liquidIcons.refresh}')
    expect(html).toContain('id="settingsToggle" class="oc-icon-btn oc-liquid-btn"')
    expect(source).toContain('id="closeHistory" class="oc-icon-btn oc-liquid-btn" type="button" title="Close history" aria-label="Close history">${liquidIcons.close}')
    expect(source).toContain("deleteButton.title = \"Delete chat history\"")
    expect(source).toContain("vscode.postMessage({ type: \"deleteSession\", sessionID: session.id })")
    expect(source).toContain('const row = document.createElement("div");')
    expect(source).toContain('const select = document.createElement("button");')
    expect(source).not.toContain('id="closeHistory" class="oc-icon-btn oc-liquid-btn" type="button" title="Close history" aria-label="Close history">${liquidIcons.discard}')
    expect(source).toContain(".headerHistoryAction")
    expect(source).toContain(".sessionDelete")
    expect(html).toContain('id="statusDot" class="oc-status-dot"')
    expect(html).toContain('class="settingsEntry oc-settings-tile oc-liquid-card" data-settings-section="connect"')
    expect(html).toContain('class="settingsEntry oc-settings-tile oc-liquid-card" data-settings-section="complete"')
    expect(html).toContain('id="completionSettingsStatus" class="settingsEntryStatus off" title="Autocomplete disabled · inline code completion is off" aria-label="Autocomplete disabled"')
    expect(html).toContain('class="settingsEntry oc-settings-tile oc-liquid-card" data-settings-section="skills"')
    expect(html).toContain('class="settingsEntry oc-settings-tile oc-liquid-card" data-settings-section="rag"')
    expect(html).toContain('class="settingsEntry oc-settings-tile oc-liquid-card" data-settings-section="guard"')
    expect(html).toContain('class="settingsEntry oc-settings-tile oc-liquid-card" data-settings-section="mcp"')
    expect(html).toContain('class="settingsSection active" data-settings-panel="connect"')
    expect(source).toContain(".settingsSection.active")
    expect(source).toContain("box-shadow: inset 2px 0 0 var(--vscode-focusBorder);")
    expect(html).toContain('id="modelTrigger" class="modelTrigger oc-chip oc-liquid-chip"')
    expect(html).toContain('id="agentTrigger" class="modelTrigger agentTrigger oc-chip oc-liquid-chip"')
    expect(html).toContain('class="composerToolbar composerPrimaryRail composerControlRail"')
    expect(html).toContain('class="composerPickerRail"')
    expect(html).toContain('id="permissionStatusPill" class="composerStatusPill permissionTrigger oc-chip oc-liquid-chip permission tools-off is-empty"')
    expect(html).not.toContain('id="permissionStatusPill" class="composerStatusPill permissionTrigger oc-chip oc-liquid-chip permission ask"')
    expect(html).toContain('class="composerActionRow toggles composerContextRail"')
    expect(html).toContain('id="composerMore" class="composerIconButton composerMoreButton oc-icon-btn oc-liquid-btn"')
    expect(html).toContain('id="composerMoreMenu" class="modelMenu composerMoreMenu"')
    expect(source).toContain('<span class="composerToggleIcon" aria-hidden="true">${liquidIcons.panelBottomClose}</span>')
    expect(source).toContain("panelBottomClose: LIQUID_ICONS.panelBottomClose")
    expect(source).toContain("panelBottomOpen: LIQUID_ICONS.panelBottomOpen")
    expect(source).not.toContain('<span class="composerToggleIcon" aria-hidden="true">${liquidIcons.more}</span>')
    expect(source).not.toContain("panelBottomClose: LIQUID_ICONS.more")
    expect(html).not.toContain('class="composerCommandRail"')
    expect(html).toContain('class="composerSupportRail" aria-label="Composer status details"')
    expect(html.indexOf('id="permissionStatusPill"')).toBeGreaterThan(html.indexOf('class="composerPickerRail"'))
    expect(html.indexOf('id="permissionStatusPill"')).toBeLessThan(html.indexOf('id="modelTrigger"'))
    expect(html).toContain('id="ragStatusPill"')
    expect(html.indexOf('id="ragStatusPill"')).toBeGreaterThan(html.indexOf('id="indexStatusPill"'))
    expect(source).toContain('button.className = "permissionModeButton oc-liquid-btn " + mode')
    expect(source).toContain('for (const mode of ["ask", "auto", "full-access"])')
    expect(source).toContain("permissionModeIcon")
    expect(source).toContain("permissionModeTitle")
    expect(source).toContain("permissionModeDesc")
    expect(source).toContain("permissionModeCheck")
    expect(source).toContain("function toolsEnabled()")
    expect(source).toContain('"工具关闭"')
    expect(source).toContain("tool: LIQUID_ICONS.tool")
    expect(source).toContain("toolsOff: LIQUID_ICONS.toolDisabled")
    expect(source).toContain("${liquidIcons.toolDisabled}")
    expect(source).not.toContain("${liquidIcons.stop}</span></button>")
    expect(source).toContain(".permissionTrigger.tools-off")
    expect(source).toContain('const kind = enabled ? (mode === "full-access" ? "full-access" : mode === "auto" ? "auto" : "ask") : "tools-off";')
    expect(source).toContain('icon: enabled ? (mode === "full-access" ? STATUS_ICONS.shieldAlert : STATUS_ICONS.shieldCheck) : STATUS_ICONS.toolsOff')
    expect(source).toContain("toggleIcon.innerHTML = STATUS_ICONS.tool;")
    expect(source).toContain("data-tools-enabled")
    expect(source).toContain("saveToolsEnabled")
    expect(source).toContain("模型工具调用")
    expect(source).toContain(".oc-liquid-icon-disabled-slash")
    expect(source).toContain("stroke: currentColor;")
    expect(source).not.toContain("var(--vscode-errorForeground, #f48771) 78%, currentColor")
    const usageStatusPill = html.match(/<button id="usageStatusPill"[^>]*>[\s\S]*?<\/button>/)?.[0] || ""
    expect(usageStatusPill).toContain('class="composerStatusPill oc-icon-btn oc-liquid-btn usage pending"')
    expect(usageStatusPill).not.toContain("compactRing")
    expect(usageStatusPill).not.toContain("statusRing")
    expect(html.indexOf('id="completionStatusPill"')).toBeGreaterThan(html.indexOf('id="usageStatusPill"'))
    expect(html.indexOf('id="completionStatusPill"')).toBeLessThan(html.indexOf('id="queueStatusPill"'))
    expect(html).toContain('id="composerProgress" class="composerProgress" aria-hidden="true"')
    expect(source).toContain("function renderComposerProgress")
    expect(source).toContain("function contextUsageProgress")
    expect(source).toContain("function formatCompactCount")
    expect(source).toContain('label: formatCompactCount(context.used) + " / " + formatCompactCount(context.limit)')
    expect(html).toContain('id="send" class="send oc-icon-btn oc-liquid-btn" type="button" title="Send" aria-label="Send message"')
    expect(html).toContain('id="selToggle" class="oc-icon-toggle oc-liquid-toggle"')
    expect(html).toContain('aria-pressed="true"')
    expect(html).toContain('id="diagToggle" class="oc-icon-toggle oc-liquid-toggle"')
    expect(html).toContain("diagnosticsBadgeText")
    expect(html).toContain("diagnosticsToggleLabel")
    expect(html).toContain("renderDiagnosticsStatusPopover")
    expect(html).toContain('["diag", "diagToggle", "diagnostics"]')
    expect(html).toContain('aria-controls", "composerStatusPopover"')
    expect(html).toContain('id="permissionStatusPill"')
    expect(html).toContain('id="skillsStatusPill"')
    expect(html).toContain("请求批准")
    expect(html).toContain("替我审批")
    expect(html).toContain("完全访问")
    expect(html).toContain('placeholder="Ask ChipMate…"')
    expect(html).toContain("Ask with context")
    expect(html).toContain("Explain file")
    expect(html).toContain("Summarize the current file.")
    expect(html).toContain("Improve the selected code.")
    expect(html).toContain("Review diff")
    expect(html).toContain("Check the current diff.")
    expect(source).toContain('prompt.className = "emptyCommand"')
    expect(source).toContain('arrow.className = "emptyCommandArrow"')
    expect(source).toContain(".emptyCommand:hover .emptyCommandArrow")
    expect(source).toContain("transform: translateX(2px);")
    expect(source).toContain(".composer:focus-within")
    expect(source).toContain("border-color: var(--vscode-focusBorder);")
    expect(source).toContain(".modelTrigger.warning")
    expect(html).toContain('id="ragCompactStatus" class="settingsStatusChip oc-chip oc-liquid-chip"')
    expect(html).toContain('class="ragActionbar oc-liquid-actionbar"')
    expect(html).not.toContain("#setRag" + "ApiKey")
    expect(html).not.toContain("Set RAG " + "API key")
    expect(html).not.toContain("Set inline completion " + "API key")
    expect(html).toContain('<label class="field">Model<select id="completionModel"></select></label>')
    expect(html).toContain('placeholder="qwen3-embedding-8b"')
    expect(html).toContain('placeholder="qwen3-reranker-8b"')
    expect(html).toContain('Batch size<select id="ragEmbeddingBatchSize"')
    expect(html).toContain('title="Embedding request timeout is automatic: 1-256 use 60s, 512 uses 90s"')
    expect(html).not.toContain('ragEmbeddingDimensions')
    expect(html).toContain('id="ragEmbeddingMaxTokensPerRequest"')
    expect(html).toContain('id="ragEmbeddingConcurrentRequests"')
    expect(html).toContain('id="ragEmbeddingMaxInFlightTokens"')
    expect(html).toContain('id="ragEmbeddingEncodingFormat"')
    expect(html).toContain("const RAG_EMBEDDING_BATCH_SIZE_DEFAULT = 64;")
    expect(html).toContain("const RAG_EMBEDDING_CONCURRENT_REQUESTS_DEFAULT = 2;")
    expect(html).toContain('const RAG_EMBEDDING_ENCODING_FORMAT_DEFAULT = "auto";')
    expect(html).toContain('embeddingConcurrentRequests: numberInputValue("ragEmbeddingConcurrentRequests", RAG_EMBEDDING_CONCURRENT_REQUESTS_DEFAULT)')
    expect(html).toContain('embeddingEncodingFormat: ragEmbeddingEncodingFormatSelectValue(el("ragEmbeddingEncodingFormat").value)')
    expect(html).toContain('id="ragEmbeddingCheckpointMode"')
    expect(html).toContain('id="ragEmbeddingCheckpointChunkInterval"')
    expect(html).toContain('id="ragEmbeddingCheckpointIntervalMs"')
    expect(html).toContain('<option value="10">10</option>')
    expect(html).toContain('<option value="512">512</option>')
    expect(html).toContain("ragEmbeddingTimeoutMsForBatchSize")
    expect(html).toContain("return Number(batchSize) === 512 ? 90000 : 60000;")
    expect(html).not.toContain('id="ragEmbeddingTimeoutMs"')
    expect(html).toContain('rag.availability === "indexing"')
    expect(html).toContain("ragElapsedMeta")
    expect(html).toContain("ragWorkerMeta")
    expect(html).toContain('", workers " + worker.activeWorkers + "/" + worker.maxWorkers')
    expect(html).toContain('worker.lastChange.direction === "upgrade" ? "upgraded" : "degraded"')
    expect(html).toContain("Not configured")
    expect(html).toContain('aria-live="polite"')
    expect(html).toContain('id="discardRagSettings"')
    expect(html).toContain("discardRagSettings")
    expect(html).not.toContain('class="secondary exportButton composerIconButton"')
    expect(html).not.toContain('el("send").textContent = state.sending ? "..." : "Send"')
  })

  test("keeps user messages visually distinct from assistant answers", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    expect(source).toContain("--chat-user-font-size: var(--chat-content-font-size);")
    expect(source).toContain("--oc-user-message-bg")
    expect(source).toContain("--oc-user-message-border")
    expect(source).toContain(".timelineItem.user {")
    expect(source).toContain("justify-self: end;")
    expect(source).toContain("background: var(--oc-user-message-bg);")
    expect(source).toContain("border: 1px solid var(--oc-user-message-border);")
    expect(source).toContain(".timelineItem.user .messageRole")
    expect(source).toContain("background: var(--oc-user-message-border);")
    expect(source).not.toContain(".messageCard,\n    .timelineItem.user .messageCard {\n      border: 0;")
  })

  test("uses role-aware copy labels for messages", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    expect(source).toContain('const copyTitle = item.role === "user" ? "Copy question text" : "Copy answer text";')
    expect(source).toContain('const copyFeedback = item.role === "user" ? "Copied question." : "Copied answer.";')
    expect(source).toContain('messageActionButton("Copy", copyTitle, "copyAnswer"')
  })

  test("does not force-scroll while streaming when the user has left the bottom", () => {
    const html = createChatViewHtml("vscode-resource:", "Scroll123")

    expect(html).toContain("let autoFollowMessages = true;")
    expect(html).toContain("let forceNextMessageFollow = false;")
    expect(html).toContain("const stick = autoFollowMessages && (userNearBottom || forceNextMessageFollow);")
    expect(html).toContain("const previousScrollTop = root.scrollTop;")
    expect(html).toContain("const maxScrollTop = Math.max(0, root.scrollHeight - root.clientHeight);")
    expect(html).toContain("root.scrollTop = Math.min(previousScrollTop, maxScrollTop);")
    expect(html).toContain("function pauseAutoFollowForUser")
    expect(html).toContain("function enableAutoFollowMessages")
    expect(html).toContain('messagesRoot.addEventListener("wheel"')
    expect(html).toContain('el("jumpLatest").addEventListener("click", jumpToLatestMessage);')
    expect(html).not.toContain("userNearBottom || Boolean(state.sending)")
    expect(html).not.toContain("state.sending && userNearBottom")
  })

  test("renders tool and thinking cards as compact grouped status rows", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    expect(source).toContain(".toolCard {\n      margin-top: 4px;")
    expect(source).toContain(".toolCard summary {\n      cursor: pointer;\n      min-height: 22px;\n      padding: 2px 7px;")
    expect(source).toContain("font-size: 10px;\n      line-height: 1.2;")
    expect(source).toContain(".toolCard pre {\n      margin: 0;\n      padding: 6px 7px;")
    expect(source).toContain(".timelineItem.thinking .messageBody {\n      min-height: 22px;")
    expect(source).toContain(".toolCard.reasoning.is-running summary {\n      display: flex;")
    expect(source).toContain(".reasoningPreview {\n      flex: 1 1 auto;\n      min-width: 0;\n      overflow: hidden;\n      text-overflow: ellipsis;\n      white-space: nowrap;")
    expect(source).toContain('label.textContent = "Thinking...";')
    expect(source).toContain('preview.className = "reasoningPreview";')
    expect(source).toContain('details.className = "toolCard"')
    expect(source).toContain('+ (part.status === "running" ? " is-running" : "");')
    expect(source).toContain('const toolParts = parts.filter((part) => part.type === "tool");')
    expect(source).toContain('details.className = "toolCard toolGroup";')
    expect(source).toContain("function toolGroupSummary(parts)")
    expect(source).toContain('"Tools: " + parts.length + " calls"')
    expect(source).toContain('toolNameCounts(parts).map((item) => item.name + " x" + item.count)')
    expect(source).toContain("function toolStatusSummary(parts)")
    expect(source).toContain("function toolGroupDetail(parts)")
    expect(source).toContain('String(index + 1) + ". " + toolSummaryLabel(part)')
    expect(source).toContain("return (item.parts || []).some((part) => part.text || part.detail || part.status);")
    expect(source).not.toContain('if (part.type !== "tool" && part.type !== "serverToolWarning" && part.type !== "reasoning") continue;')
  })

  test("keeps chat scrolling owned by the message list and contained nested blocks", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    expect(source).toContain("html, body {\n      height: 100%;\n      overflow: hidden;")
    expect(source).toContain("overscroll-behavior: none;\n      overflow-anchor: none;")
    expect(source).toContain(".messages {\n      flex: 1;\n      min-height: 0;\n      overflow: auto;\n      overscroll-behavior: contain;\n      overflow-anchor: none;")
    expect(source).not.toContain(".messageCard.longAnswer:not(.longExpanded) .messageBody")
    expect(source).not.toContain("max-height: min(620px, 72vh);")
    expect(source).not.toContain("Long answer limited for performance. Use Full to expand.")
    expect(source).not.toContain("expandedLongMessages")
    expect(source).not.toContain("toggleLongMessage")
    expect(source).not.toContain("expandLong")
    expect(source).toContain(".tableScroll {\n      width: 100%;\n      overflow-x: auto;\n      overflow-y: hidden;\n      overscroll-behavior-x: contain;\n      overscroll-behavior-y: auto;")
    expect(source).toContain(".tableRaw {\n      display: none;\n      margin: 0;\n      overflow-x: auto;\n      overflow-y: visible;")
    expect(source).toContain(".tableRaw {\n      display: none;\n      margin: 0;\n      overflow-x: auto;\n      overflow-y: visible;\n      overscroll-behavior-x: contain;\n      overscroll-behavior-y: auto;")
    expect(source).toContain(".codeBlock pre {\n      margin: 0;\n      padding: 10px;\n      overflow-x: auto;\n      overflow-y: visible;")
    expect(source).toContain(".codeBlock pre {\n      margin: 0;\n      padding: 10px;\n      overflow-x: auto;\n      overflow-y: visible;\n      overscroll-behavior-x: contain;\n      overscroll-behavior-y: auto;")
    expect(source).toContain(".toolCard pre {\n      margin: 0;\n      padding: 6px 7px;\n      overflow-x: auto;\n      overflow-y: visible;\n      overscroll-behavior-x: contain;\n      overscroll-behavior-y: auto;")
    expect(source).not.toContain(".codeBlock pre {\n      margin: 0;\n      padding: 10px;\n      overflow-x: auto;\n      overflow-y: visible;\n      overscroll-behavior: contain;")
    expect(source).not.toContain(".tableScroll {\n      width: 100%;\n      overflow-x: auto;\n      overflow-y: hidden;\n      overscroll-behavior: contain;")
  })

  test("routes vertical wheel gestures from nested horizontal scrollers to the chat list", () => {
    const html = createChatViewHtml("vscode-resource:", "WheelRoute123")

    expect(html).toContain('messagesRoot.addEventListener("wheel", (event) => {')
    expect(html).toContain("if (redirectNestedVerticalWheel(event, messagesRoot)) return;")
    expect(html).toContain("}, { capture: true, passive: false });")
    expect(html).toContain("function redirectNestedVerticalWheel(event, root)")
    expect(html).toContain("const nested = nestedMessageScroller(event.target);")
    expect(html).toContain("if (!isPlainVerticalWheel(event)) {")
    expect(html).toContain("event.preventDefault();")
    expect(html).toContain("root.scrollTop += event.deltaY;")
    expect(html).toContain("handleMessagesScroll(root);")
    expect(html).toContain("function isPlainVerticalWheel(event)")
    expect(html).toContain("if (event.shiftKey) return false;")
    expect(html).toContain("Math.abs(event.deltaY) > Math.abs(event.deltaX)")
    expect(html).toContain("function nestedMessageScroller(target)")
    expect(html).toContain('node.closest(".codeBlock pre, .diagramCanvas, .diagramSource, .tableScroll, .tableRaw, .messageOutline, .toolCard pre")')
  })

  test("preserves horizontal scroll positions across streaming rerenders", () => {
    const html = createChatViewHtml("vscode-resource:", "NestedScroll123")

    expect(html).toContain("function collectMessageHorizontalScrollState")
    expect(html).toContain('root.querySelectorAll(".messageCard[data-message-key]")')
    expect(html).toContain('outlineScrollLeft: Array.from(card.querySelectorAll(".messageOutline")).map((node) => node.scrollLeft)')
    expect(html).toContain('codeScrollLeft: Array.from(card.querySelectorAll(".codeBlock pre")).map((node) => node.scrollLeft)')
    expect(html).toContain('diagramScrollLeft: Array.from(card.querySelectorAll(".diagramCanvas, .diagramSource")).map((node) => node.scrollLeft)')
    expect(html).toContain('tableScrollLeft: Array.from(card.querySelectorAll(".tableScroll")).map((node) => node.scrollLeft)')
    expect(html).toContain("function restoreMessageHorizontalScrollState")
    expect(html).toContain('restoreNestedScrollList(card.querySelectorAll(".codeBlock pre"), saved && saved.codeScrollLeft, "scrollLeft");')
    expect(html).toContain('restoreNestedScrollList(card.querySelectorAll(".diagramCanvas, .diagramSource"), saved && saved.diagramScrollLeft, "scrollLeft");')
    expect(html).not.toContain("bodyScrollTop")
    expect(html).not.toContain("body.scrollTop")
  })

  test("reuses keyed message DOM while streaming instead of rebuilding the whole timeline", () => {
    const html = createChatViewHtml("vscode-resource:", "KeyedRender123")
    const renderStart = html.indexOf("function renderMessages")
    const renderEnd = html.indexOf("function reconcileMessageNodes", renderStart)
    const renderBody = html.slice(renderStart, renderEnd)
    const reconcileStart = html.indexOf("function reconcileMessageNodes")
    const reconcileEnd = html.indexOf("function updateExistingMessageNode", reconcileStart)
    const reconcileBody = html.slice(reconcileStart, reconcileEnd)

    expect(html).toContain("function reconcileMessageNodes")
    expect(html).toContain("function updateExistingMessageNode")
    expect(html).toContain('node.setAttribute("data-message-key", messageKey);')
    expect(html).toContain('node.setAttribute("data-message-fingerprint", messageRenderFingerprint(item, index, messageKey));')
    expect(html).toContain('node.className = replacement.className + " streamStable";')
    expect(html).toContain('node.setAttribute("data-stream-stable", "true");')
    expect(html).toContain('const currentCard = directChildWithClass(node, "messageCard");')
    expect(html).toContain("replaceElementContents(currentCard, replacementCard);")
    expect(html).toContain("function syncElementAttributes")
    expect(html).toContain(".timelineItem.streamStable { animation: none; }")
    expect(html).toContain("function messageRenderFingerprint")
    expect(renderBody).toContain("reconcileMessageNodes(root, entries);")
    expect(reconcileBody).toContain("if (node) return updateExistingMessageNode(node, entry);")
    expect(reconcileBody).not.toContain("node.replaceWith")
    expect(renderBody).not.toContain('root.innerHTML = "";')
  })

  test("throttles high-frequency streaming state posts while flushing terminal stream events", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")
    const handleStart = source.indexOf("private handleRemoteEvent")
    const handleEnd = source.indexOf("private showChatInterruptedWarning", handleStart)
    const handleBody = source.slice(handleStart, handleEnd)

    expect(source).toContain("STREAMING_STATE_POST_THROTTLE_MS = 50")
    expect(source).toContain("new StreamingStatePostScheduler(")
    expect(source).toContain("private scheduleStreamingStatePost()")
    expect(source).toContain("private flushStreamingStatePost()")
    expect(source).toContain("function isHighFrequencyStreamingMessageEvent")
    expect(handleBody).toContain("if (isHighFrequencyStreamingMessageEvent(event.type)) this.scheduleStreamingStatePost()")
    expect(handleBody).toContain("else this.postState()")
    expect(handleBody.match(/this\.flushStreamingStatePost\(\)/g)?.length).toBeGreaterThanOrEqual(4)
  })

  test("scrolls message structure navigation inside the nearest chat scroller", () => {
    const html = createChatViewHtml("vscode-resource:", "StructureScroll123")

    expect(html).toContain("function scrollToMessageTarget")
    expect(html).toContain("pauseAutoFollowForUser();")
    expect(html).toContain('scrollTargetWithinContainer(target, el("messages"));')
    expect(html).toContain('root.querySelectorAll(".codeBlock, .diagramBlock, .tableBlock")')
    expect(html).toContain('const diagrams = Array.from(body.querySelectorAll(".diagramBlock"));')
    expect(html).toContain('" diagram / "')
    expect(html).toContain("function scrollTargetWithinContainer")
    expect(html).toContain('container.scrollTo({ top, behavior: "smooth" })')
    expect(html).not.toContain('target.closest(".messageCard.longAnswer')
    expect(html).not.toContain("target.scrollIntoView(")
  })

  test("keeps permission popover buttons readable across composer widths", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")
    const liquidButtonRule = source.indexOf(".oc-tool-btn,\n    .oc-icon-btn,\n    .oc-icon-toggle,\n    .oc-liquid-btn,")
    const permissionOverride = source.indexOf(".composerStatusPopover.permissionPopover .permissionModeButton.oc-liquid-btn")

    expect(liquidButtonRule).toBeGreaterThan(-1)
    expect(permissionOverride).toBeGreaterThan(liquidButtonRule)
    expect(source).toContain("container-name: composer-shell;")
    expect(source).toContain("container-type: inline-size;")
    expect(source).toContain("width: min(320px, calc(100vw - 24px));")
    expect(source).toContain("max-width: none;")
    expect(source).not.toContain("max-width: calc(100% - 16px);")
    expect(source).toContain("overflow-x: hidden;")
    expect(source).toContain("display: grid;\n      grid-template-columns: 24px minmax(0, 1fr) 18px;")
    expect(source).toContain("width: 100%;\n      max-width: none;\n      min-width: 0;")
    expect(source).toContain("height: auto;\n      min-height: 58px;")
    expect(source).toContain(".toolsToggleButton")
    expect(source).toContain(".composerStatusPopover.permissionPopover .toolsToggleButton.oc-liquid-btn")
    expect(source).toContain("grid-template-columns: 24px minmax(0, 1fr) 42px;")
    expect(source).toContain(".toolsToggleTrack")
    expect(source).not.toContain("@container composer-shell (max-width: 360px)")
    expect(source).toContain("@media (max-width: 360px)")
    expect(source).toContain("width: min(308px, calc(100vw - 18px));")
    expect(source).toContain("grid-template-columns: 20px minmax(0, 1fr) 38px;")
    expect(source).toContain("grid-template-columns: 20px minmax(0, 1fr) 16px;")
    expect(source).not.toContain("max-width: calc(100% - 12px);")
  })

  test("keeps composer controls stable in narrow prompt widths", () => {
    const html = createChatViewHtml("vscode-resource:", "NarrowComposer123")
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    expect(source).toContain("container-name: composer;")
    expect(source).toContain("container-type: inline-size;")
    expect(source).toContain("@container composer (max-width: 420px)")
    const narrowStart = source.indexOf("@container composer (max-width: 420px)")
    const tightStart = source.indexOf("@container composer (max-width: 300px)", narrowStart)
    const forcedColorsStart = source.indexOf("@media (forced-colors: active)", tightStart)
    expect(narrowStart).toBeGreaterThan(-1)
    expect(tightStart).toBeGreaterThan(narrowStart)
    expect(forcedColorsStart).toBeGreaterThan(tightStart)
    const narrowBlock = source.slice(narrowStart, tightStart)
    const tightBlock = source.slice(tightStart, forcedColorsStart)

    expect(narrowBlock).toContain(".composerPickerRail .permissionTrigger")
    expect(narrowBlock).toContain(".composerPickerRail .skillsTrigger")
    expect(narrowBlock).toContain("flex: 0 0 30px;")
    expect(narrowBlock).toContain(".composerPickerRail .permissionTrigger .pillLabelText")
    expect(narrowBlock).toContain(".composerPickerRail .skillsTrigger .pillLabelText")
    expect(narrowBlock).toContain("display: none;")
    expect(narrowBlock).toContain("flex: 1 1 96px;")
    expect(narrowBlock).toContain("min-width: 74px;")
    expect(narrowBlock).not.toContain(".composerPickerRail .modelTrigger .oc-liquid-chip-label")
    expect(narrowBlock).not.toContain(".composerPickerRail .agentTrigger .oc-liquid-chip-label")
    expect(tightBlock).toContain(".composerPickerRail .modelTrigger .oc-liquid-chip-label")
    expect(tightBlock).toContain(".composerPickerRail .agentTrigger .oc-liquid-chip-label")
    expect(narrowBlock).not.toContain("position: absolute")
    expect(tightBlock).not.toContain("position: absolute")
    expect(narrowBlock).not.toContain("clip-path: inset(50%);")
    expect(tightBlock).not.toContain("clip-path: inset(50%);")
    expect(source).toContain("flex-wrap: nowrap;")
    expect(source).toContain("margin-inline-start: 0;")
    expect(html).toContain('id="permissionStatusPill" class="composerStatusPill permissionTrigger oc-chip oc-liquid-chip permission tools-off is-empty"')
    expect(html).toContain('id="send" class="send oc-icon-btn oc-liquid-btn" type="button" title="Send" aria-label="Send message"')
  })

  test("surfaces RAG as an independent composer progress ring without changing code graph", () => {
    const html = createChatViewHtml("vscode-resource:", "RagRing123")
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")

    const indexStatusPill = html.match(/<button id="indexStatusPill"[^>]*>[\s\S]*?<\/button>/)?.[0] || ""
    const ragStatusPill = html.match(/<button id="ragStatusPill"[^>]*>[\s\S]*?<\/button>/)?.[0] || ""

    expect(indexStatusPill).toContain('class="composerStatusPill oc-icon-btn oc-liquid-btn index info compactRing"')
    expect(source).toContain('id="indexStatusPill" class="composerStatusPill oc-icon-btn oc-liquid-btn index info compactRing" type="button" title="Show index details"><span class="pillText statusRing" aria-hidden="true">${liquidIcons.database}</span></button>')
    expect(ragStatusPill).toContain('class="composerStatusPill oc-icon-btn oc-liquid-btn rag info compactRing"')
    expect(source).toContain('id="ragStatusPill" class="composerStatusPill oc-icon-btn oc-liquid-btn rag info compactRing" type="button" title="Show RAG index details"><span class="pillText statusRing" aria-hidden="true">${liquidIcons.searchIndex}</span></button>')
    expect(html.indexOf('id="ragStatusPill"')).toBeGreaterThan(html.indexOf('id="indexStatusPill"'))
    expect(html).toContain("bindComposerStatusPill(\"ragStatusPill\", \"rag\", true)")
    expect(html).toContain("function composerRagStatus")
    expect(html).toContain("function ragStatusView")
    expect(html).toContain("function ragStatusRing")
    expect(html).toContain("function renderRagStatusPopover")
    expect(html).toContain('if (activePopover === "rag") renderRagStatusPopover(root);')
    expect(html).toContain("openRagSettingsFromPopover")
    expect(html).toContain("data-open-rag-settings")
    expect(html).toContain("ragControlActions(rag)")
    expect(html).toContain('message: "pauseRagIndexing"')
    expect(html).toContain('message: "resumeRagIndexing"')
    expect(html).toContain('message: "cancelRagIndexing"')
  })

  test("surfaces Complete status with a completion-specific icon and explanatory popover", () => {
    const html = createChatViewHtml("vscode-resource:", "CompleteStatus123")
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")
    const completionButton = source.match(/id="completionStatusPill"[\s\S]*?<\/button>/)?.[0] || ""
    const completeTile = source.match(/data-settings-section="complete"[\s\S]*?<\/button>/)?.[0] || ""
    const statusIconSource = source.slice(source.indexOf("function autocompleteStatusIcon"), source.indexOf("export function createNonce"))
    const completionIconCss = source.slice(
      source.indexOf("    .composerStatusPill.completion .pillText"),
      source.indexOf("    .composerStatusPill.hasText .pillLabelText"),
    )

    expect(html).toContain('id="completionStatusPill"')
    expect(html.indexOf('id="completionStatusPill"')).toBeGreaterThan(html.indexOf('id="usageStatusPill"'))
    expect(html.indexOf('id="completionStatusPill"')).toBeLessThan(html.indexOf('id="queueStatusPill"'))
    expect(completionButton).toContain("${autocompleteStatusIcons.disabled}")
    expect(completionButton).not.toContain("${liquidIcons.sparkle}")
    expect(completionButton).not.toContain("${liquidIcons.database}")
    expect(completionButton).not.toContain("${liquidIcons.shield}")
    expect(completionButton).not.toContain("${liquidIcons.more}")
    expect(completionButton).not.toContain("${liquidIcons.server}")
    expect(completeTile).toContain("${liquidIcons.completion}")
    expect(completeTile).toContain('id="completionSettingsStatus"')
    expect(completeTile).not.toContain("${liquidIcons.sparkle}")
    expect(html).toContain('bindComposerStatusPill("completionStatusPill", "completion", true)')
    expect(html).toContain('if (activePopover === "completion") renderCompletionStatusPopover(root);')
    expect(html).toContain("function renderCompletionStatusPopover")
    expect(html).toContain('data-open-complete-settings')
    expect(html).toContain("openCompleteSettingsFromPopover")
    expect(html).toContain("Autocomplete enabled · inline code completion is available")
    expect(html).toContain("Autocomplete disabled · inline code completion is off")
    expect(html).toContain("Autocomplete unavailable · no Qwen Coder completion model was returned by the provider")
    expect(html).toContain('ariaLabel: "Autocomplete enabled"')
    expect(html).toContain('ariaLabel: "Autocomplete disabled"')
    expect(html).toContain('ariaLabel: "Autocomplete unavailable"')
    expect(html).toContain('iconState: "enabled"')
    expect(html).toContain('iconState: "disabled"')
    expect(html).toContain('#completionStatusPill')
    expect(source).toContain("const autocompleteStatusIcons = {")
    expect(source).toContain('viewBox="0 0 20 20"')
    expect(html).toContain("autocompleteStatusIcon-enabled")
    expect(html).toContain("autocompleteStatusIcon-disabled")
    expect(source).toContain("var(--vscode-testing-iconPassed, #3fb950)")
    expect(source).toContain("var(--vscode-testing-iconFailed, #f85149)")
    expect(source).toContain("M2.5 2.9 C5.2 2.9 6.4 4.2 6.4 6.6")
    expect(source).toContain("M7.2 2.9 C9.9 2.9 11.1 4.2 11.1 6.6")
    expect(statusIconSource).toContain('cx="16.55" cy="16.45" r="2.05"')
    expect(statusIconSource).not.toContain('cx="16.4" cy="16.3" r="2.35"')
    expect(source).not.toContain('cx="16.6" cy="16.3" r="2.75"')
    expect(source).not.toContain('cx="15.7" cy="15.2" r="3.25"')
    expect(source).not.toContain('cx="15" cy="15" r="4"')
    expect(completionIconCss).toContain("stroke-width: 1.85;")
    expect(completionIconCss).toContain("stroke-width: 1.1;")
    expect(completionIconCss).toContain("stroke-width: 0.9;")
    expect(completionIconCss).toContain("opacity: 0.78;")
    expect(completionIconCss).toContain(".composerStatusPill.completion .pillText")
    expect(completionIconCss).toContain(".composerStatusPill.completion .pillGlyph")
    expect(completionIconCss).toContain(".composerStatusPill.completion .autocompleteStatusIcon")
    expect(completionIconCss).toContain("width: 17px;")
    expect(completionIconCss).toContain("height: 17px;")
    expect(completionIconCss).toContain("min-width: 17px;")
    expect(completionIconCss).toContain("flex: 0 0 17px;")
    expect(completionIconCss).not.toContain("width: 18px;")
    expect(completionIconCss).not.toContain("height: 18px;")
    expect(source).not.toContain(".composerStatusPill.completion.hasText .pillGlyph")
    expect(statusIconSource).toContain("M15.4 16.15 L16.1 16.85 L17.45 15.35")
    expect(statusIconSource).toContain("M4.45 15.75 L15.55 4.65")
    expect(statusIconSource).toContain("M15.55 15.45 L17.25 17.15")
    expect(statusIconSource).toContain("M17.25 15.45 L15.55 17.15")
    expect(statusIconSource).not.toContain("M4.2 16 L15.7 4.4")
    expect(statusIconSource).not.toContain("M15.35 15.25 L17.45 17.35")
    expect(source.indexOf("M4.45 15.75 L15.55 4.65")).toBeLessThan(source.indexOf("M2.5 2.9 C5.2 2.9 6.4 4.2 6.4 6.6"))
    expect(source).toContain("completion: LIQUID_ICONS.completion")
    expect(source).toContain(".composerStatusPill.completion.ready")
    expect(source).toContain(".composerStatusPill.completion.warning")
    expect(source).toContain(".settingsEntryStatus.ready")
    expect(source).toContain(".settingsEntryStatus.warning")
  })

  test("surfaces RAG indexing pause and resume controls when code graph is ready", () => {
    const html = createChatViewHtml("vscode-resource:", "RagPause123")

    expect(html).toContain("function ragControlActions")
    expect(html).toContain('rag.availability === "indexing"')
    expect(html).toContain('rag.availability === "paused"')
    expect(html).toContain('message: "pauseRagIndexing"')
    expect(html).toContain('message: "resumeRagIndexing"')
    expect(html).toContain('message: "cancelRagIndexing"')
    expect(html).toContain('id="toggleRagIndexing"')
    expect(html).toContain("function renderRagIndexingControl")
    expect(html).toContain("function toggleRagIndexing")
    const ragActionsStart = html.indexOf("function ragControlActions")
    const ragActionsEnd = html.indexOf("function codeGraphView", ragActionsStart)
    const ragActionsBody = html.slice(ragActionsStart, ragActionsEnd)
    expect(ragActionsBody).not.toContain('message: "pauseCodeGraph"')
    expect(ragActionsBody).not.toContain('message: "resumeCodeGraph"')
    expect(ragActionsBody).not.toContain('message: "cancelCodeGraph"')
    expect(html).toContain("paused by user")
  })

  test("keeps webview actions and accessibility hooks wired", () => {
    const html = createChatViewHtml("vscode-resource:", "Actions123")

    expect(html).toContain('el("syncState").addEventListener("click", () => vscode.postMessage({ type: "refresh" }))')
    expect(html).toContain('vscode.postMessage({ type: "cancelSend" })')
    expect(html).toContain("onSendButtonClick")
    expect(html).toContain('setSendButtonContent(button, cancellable ? "stop" : "send", label, loading)')
    expect(html).toContain('button.classList.toggle("is-loading", loading)')
    expect(html).toContain("sendSpinner")
    expect(html).toContain("Select an agent before sending")
    expect(html).toContain("toggleComposerMoreMenu")
    expect(html).toContain("bindContextToggle")
    expect(html).toContain("renderComposerToggles")
    expect(html).toContain("setChipLabel")
    expect(html).toContain("setIconOnlyButton")
    expect(html).toContain("setButtonTemporaryLabel")
    expect(html).toContain('type: "exportMarkdown", scope: "session"')
    expect(html).toContain('event.data.type === "exportStatus"')
    expect(html).toContain('type: "saveRagSettings"')
    expect(html).toContain('type: "testRagSettings"')
    expect(html).not.toContain('type: "setRag' + 'ApiKey"')
    expect(html).toContain("forced-colors: active")
    expect(html).toContain("prefers-reduced-motion")
  })

  test("queues composer sends while streaming without stealing Stop from empty drafts", () => {
    const html = createChatViewHtml("vscode-resource:", "Queue123")

    expect(html).toContain("function hasComposerDraft()")
    expect(html).toContain("if (state.sending && !hasComposerDraft())")
    expect(html).toContain("const queueing = Boolean(state.sending);")
    expect(html).toContain("if (queueing && queueIsFull())")
    expect(html).toContain("function queuedNoticeAfterSubmit()")
    expect(html).toContain("let optimisticQueuedSends = [];")
    expect(html).toContain("function nextClientQueueID()")
    expect(html).toContain("clientQueueID: clientQueueID || undefined")
    expect(html).toContain("optimisticQueuedSends = [")
    expect(html).toContain("renderQueuedSendList();\n\t        renderComposerStatusBar();\n\t        renderSendButton();")
    expect(html).toContain("Queued \" + queuedSendCount()")
    expect(html).toContain("const queueing = Boolean(state.sending && hasComposerDraft());")
    expect(html).toContain('button.classList.toggle("is-queued", queueing)')
    expect(html).toContain('label = blockedByGuard && !state.sending')
    expect(html).toContain('event.data.type === "queueStatus"')
    expect(html).toContain('event.data.type === "queueUpdated"')
    expect(html).toContain('event.data.type === "queueRejected"')
    expect(html).toContain("function applyQueueSnapshot")
    expect(html).toContain("function handleQueueRejected")
    expect(html).toContain("function reconcileOptimisticQueuedSends")
    expect(html).toContain("function normalizeQueuedSends")
    expect(html).toContain("function composerQueueStatus")
    expect(html).toContain('id="queueStatusPill"')
    expect(html).toContain('bindComposerStatusPill("queueStatusPill", "queue", true)')
    expect(html).toContain('if (activePopover === "queue") renderQueueStatusPopover(root);')
    expect(html).toContain('id="queuedSendList"')
    expect(html).toContain("function renderQueuedSendList")
    expect(html).toContain("function queuedSendNode")
    expect(html).toContain('setIconOnlyButton(edit, "edit", pending ? "Waiting for queue confirmation" : "Edit queued message")')
    expect(html).not.toContain('setIconOnlyButton(edit, "apply", "Edit queued message")')
    expect(html).toContain("edit.disabled = pending")
    expect(html).toContain("remove.disabled = pending")
    expect(html).toContain('parts.push("Pending")')
    expect(html).toContain("return canonical.concat(pending);")
    expect(html).toContain('vscode.postMessage({ type: "editQueuedSend", id: item.id })')
    expect(html).toContain('vscode.postMessage({ type: "deleteQueuedSend", id: item.id })')
    expect(html).toContain('event.data.type === "restoreQueuedSendDraft"')
    expect(html).toContain("function restoreQueuedSendDraft")
    expect(html).toContain(".queuedSendList")
    expect(html).not.toContain(".timelineItem.queued")
    expect(html).not.toContain("queued: Boolean(item.queued)")
  })

  test("renders context attachments as composer chips instead of a count badge", () => {
    const html = createChatViewHtml("vscode-resource:", "ContextChips123")

    expect(html).toContain('id="contextChips" class="contextChips"')
    expect(html).toContain("function renderContextChips")
    expect(html).toContain("function contextItemChip")
    expect(html).toContain("function selectedContextItem")
    expect(html).toContain("Selection · ")
    expect(html).toContain("contextPreview")
    expect(html).toContain('vscode.postMessage({ type: "removeContextItem"')
    expect(html).toContain('vscode.postMessage({ type: "openContextItem"')
    expect(html).toContain('badgeText: ""')
    expect(html).not.toContain("badgeText: count > 0")
  })

  test("supports workspace file drops as current-message attachments", () => {
    const html = createChatViewHtml("vscode-resource:", "Drop123")

    expect(html).toContain("function bindComposerDropTarget")
    expect(html).toContain('composer.addEventListener("dragenter", onComposerDragEnter)')
    expect(html).toContain('composer.addEventListener("dragover", onComposerDragOver)')
    expect(html).toContain('composer.addEventListener("dragleave", onComposerDragLeave)')
    expect(html).toContain('composer.addEventListener("drop", onComposerDrop)')
    expect(html).toContain("event.preventDefault();")
    expect(html).toContain("extractDroppedFileCandidates")
    expect(html).toContain('vscode.postMessage({ type: "addDroppedFiles", candidates })')
    expect(html).toContain('event.data.type === "droppedFilesResolved"')
    expect(html).toContain("function addDroppedMentionFiles")
    expect(html).toContain("mentionedFiles = mentionedFiles.concat(added);")
    expect(html).toContain("saveComposerDraft();")
    expect(html).toContain('class="composer"')
    expect(html).toContain(".composer.is-drop-target")
    expect(html).not.toContain("composerDropOverlay")
  })

  test("supports current-session prompt keyboard history in the composer", () => {
    const html = createChatViewHtml("vscode-resource:", "PromptHistory123")
    const keydownStart = html.indexOf("function onComposerKeydown")
    const keydownEnd = html.indexOf("function syncPromptHistoryFromState", keydownStart)
    const keydownBody = html.slice(keydownStart, keydownEnd)
    const historyStart = html.indexOf("function syncPromptHistoryFromState")
    const historyEnd = html.indexOf("function onComposerInput", historyStart)
    const historyBody = html.slice(historyStart, historyEnd)

    expect(html).toContain('let promptHistorySessionID = "";')
    expect(html).toContain("let promptHistoryEntries = [];")
    expect(html).toContain('let promptHistorySignature = "";')
    expect(html).toContain("let promptHistoryIndex = -1;")
    expect(html).toContain('let promptHistoryDraft = "";')
    expect(html).toContain("let restoringPromptHistory = false;")
    expect(html).toContain("syncPromptHistoryFromState();")
    expect(html).toContain("appendPromptHistoryEntry(text);")
    expect(html).toContain("resetPromptHistoryNavigation();")

    expect(keydownBody).toContain('const suggestionsOpen = el("suggestions").classList.contains("open");')
    expect(keydownBody.indexOf("handlePromptHistoryKeydown(event)")).toBeGreaterThan(keydownBody.indexOf("const suggestionsOpen"))
    expect(keydownBody.indexOf("handlePromptHistoryKeydown(event)")).toBeLessThan(keydownBody.indexOf("if (!suggestionsOpen) return;"))
    expect(keydownBody).toContain('if (event.key === "ArrowDown")')
    expect(keydownBody).toContain('} else if (event.key === "ArrowUp")')

    expect(historyBody).toContain("function promptHistoryEntriesFromMessages(messages)")
    expect(historyBody).toContain('item.role === "user"')
    expect(historyBody).toContain('typeof item.text === "string"')
    expect(historyBody).toContain("item.text.trim()")
    expect(historyBody).toContain("function mergePromptHistoryEntries(entries)")
    expect(historyBody).toContain("if (promptHistoryEntries.length <= entries.length) return entries;")
    expect(historyBody).toContain("return promptHistoryEntries;")
    expect(historyBody).toContain('const sessionID = String(state.currentSessionID || "");')
    expect(historyBody).toContain("sessionID === promptHistorySessionID ? mergePromptHistoryEntries(stateEntries) : stateEntries")
    expect(historyBody).toContain("if (sessionID !== promptHistorySessionID)")
    expect(historyBody).toContain("promptHistoryEntries = entries;")
    expect(historyBody).toContain("resetPromptHistoryNavigation();")
    expect(historyBody).toContain("function appendPromptHistoryEntry(text)")
    expect(historyBody).toContain("promptHistoryEntries = promptHistoryEntries.concat(prompt);")
    expect(historyBody).toContain("function handlePromptHistoryKeydown(event)")
    expect(historyBody).toContain("event.altKey || event.ctrlKey || event.metaKey || event.shiftKey")
    expect(historyBody).toContain('if (event.key !== "ArrowUp" && event.key !== "ArrowDown") return false;')
    expect(historyBody).toContain('if (input.value.trim() && promptHistoryIndex < 0) return false;')
    expect(historyBody).toContain("if (promptHistoryIndex < 0) promptHistoryDraft = input.value;")
    expect(historyBody).toContain("Math.max(0, promptHistoryIndex - 1)")
    expect(historyBody).toContain("setComposerInputFromPromptHistory(promptHistoryEntries[nextIndex]);")
    expect(historyBody).toContain("if (promptHistoryIndex < 0) return false;")
    expect(historyBody).toContain("setComposerInputFromPromptHistory(promptHistoryDraft);")
    expect(historyBody).toContain("function setComposerInputFromPromptHistory(value)")
    expect(historyBody).toContain("restoringPromptHistory = true;")
    expect(historyBody).toContain("input.setSelectionRange(input.value.length, input.value.length);")
    expect(historyBody).toContain("onComposerInput();")
    expect(historyBody).toContain("finally {")
    expect(historyBody).toContain("restoringPromptHistory = false;")
    expect(html).toContain("if (!restoringPromptHistory) resetPromptHistoryNavigation();")
  })

  test("uses mutually exclusive connection, chat, and settings modes", () => {
    const html = createChatViewHtml("vscode-resource:", "Modes123")

    expect(html).toContain("mode-connection-only")
    expect(html).toContain("mode-settings-page")
    expect(html).toContain('id="completionSettingsGroup"')
    expect(html).toContain('id="completionProfile"')
    expect(html).toContain('<label class="field">Model<select id="completionModel"></select></label>')
    expect(html).toContain('id="refreshCompletionModels"')
    expect(html).toContain('value="qwen-coder-fim"')
    expect(html).toContain('profile: el("completionProfile").value')
    expect(html).toContain('el("completionProfile").value = completion.profile || "qwen-coder-fim";')
    expect(html).toContain('renderCompletionModelSelect(completion.model || "qwen-coder-30b0")')
    expect(html).toContain("function qwenCoderCompletionModels()")
    expect(html).toContain('model.source !== "provider"')
    expect(html).toContain('No Qwen Coder completion model')
    expect(html).toContain("无可用补全模型，补全暂不可用")
    expect(html).toContain('el("ragEmbeddingModel").value = embedding.model || "qwen3-embedding-8b";')
    expect(html).toContain('el("ragRerankModel").value = rerank.model || "qwen3-reranker-8b";')
    expect(html).toContain(".app.mode-connection-only .settingsSection[data-settings-panel=\"connect\"]")
    expect(html).toContain(".app.mode-connection-only .body")
    expect(html).toContain(".app.mode-settings-page .body { display: none; }")
    expect(html).toContain('el("app").className = "app mode-" + mode')
    expect(html).toContain("function currentViewMode()")
    expect(html).toContain('return (state.connectionState || "disconnected") === "connected" ? "chat" : "connection-only";')
    expect(html).toContain("let connectionRequestId = 0;")
    expect(html).toContain("let pendingConnectionRequestId = 0;")
    expect(html).toContain('const shouldCloseSettings = !pendingAction && nextConnectionState === "connected" && lastConnectionState !== "connected";')
    expect(html).toContain('if (event.data.type === "connectionStatus")')
    expect(html).toContain("event.data.requestId !== pendingConnectionRequestId")
    expect(html).toContain('pendingAction = "";')
    expect(html).toContain("pendingConnectionRequestId = 0;")
    expect(html).toContain("if (pendingAction) return;")
    expect(html).toContain("const requestId = ++connectionRequestId;")
    expect(html).toContain("pendingConnectionRequestId = requestId;")
    expect(html).toContain("requestId,")
    expect(html).toContain("Saving and verifying provider settings. Wait for the current save to finish.")
    expect(html).toContain("Testing provider connection. Wait for the current test to finish.")
    expect(html).toContain('const password = el("password").value;')
    expect(html).toContain("if (password) payload.password = password;")
    expect(html).toContain("vscode.postMessage(payload);")
    expect(html).toContain('el("password").value = "";')
    expect(html).not.toContain('password: el("password").value')
    expect(html).not.toContain('settingsOpen || state.connectionState !== "connected"')
  })

  test("does not auto-refresh when the webview resolves", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")
    const start = source.indexOf("resolveWebviewView")
    const end = source.indexOf("setConnectionState", start)
    const resolveBody = source.slice(start, end)

    expect(resolveBody).not.toContain("refresh()")
    expect(resolveBody).toContain("postState()")
  })

  test("persists unsent composer draft in webview state", () => {
    const html = createChatViewHtml("vscode-resource:", "Draft123")

    expect(html).toContain("const restoredComposerDraft = composerDraftFromWebviewState();")
    expect(html).toContain("restoreComposerDraft();")
    expect(html).toContain("function composerDraftFromWebviewState()")
    expect(html).toContain("const draft = webviewState().composerDraft;")
    expect(html).toContain("function saveComposerDraft()")
    expect(html).toContain("vscode.setState({")
    expect(html).toContain("composerDraft: {")
    expect(html).toContain("text,")
    expect(html).toContain("mentionedFiles: files")
    expect(html).toContain("function clearComposerDraft()")
    expect(html).toContain("delete nextState.composerDraft;")
    expect(html).toContain("function webviewState()")
    expect(html).toContain("const value = vscode.getState();")
    expect(html).toContain("function normalizeDraftMentionedFiles(files)")
    expect(html).toContain("saveComposerDraft();")
    expect(html).toContain("clearComposerDraft();")
  })

  test("checks markdown lists before aligned table detection", () => {
    const html = createChatViewHtml("vscode-resource:", "Order123")
    const start = html.indexOf("function renderTextMarkdown")
    const end = html.indexOf("function detectTableBlock", start)
    const renderText = html.slice(start, end)

    expect(renderText.indexOf("const unordered")).toBeGreaterThan(-1)
    expect(renderText.indexOf("const ordered")).toBeGreaterThan(-1)
    expect(renderText.indexOf("const table = detectTableBlock(lines, index)")).toBeGreaterThan(-1)
    expect(renderText.indexOf("const unordered")).toBeLessThan(renderText.indexOf("const table = detectTableBlock(lines, index)"))
    expect(html).toContain("looksLikeMarkdownListRows(rows) || looksLikeMarkdownLabelRows(rows)")
    expect(html).toContain("isMarkdownListMarkerCell(row[0])")
    expect(html).toContain("String.fromCharCode(0xff1a)")
  })

  test("chat provider handles code graph, export, and cancel webview actions", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")

    expect(source).toContain('{ type: "indexCodeGraph" }')
    expect(source).toContain('{ type: "rebuildCodeGraph" }')
    expect(source).toContain('{ type: "pauseCodeGraph" }')
    expect(source).toContain('{ type: "resumeCodeGraph" }')
    expect(source).toContain('{ type: "cancelCodeGraph" }')
    expect(source).toContain('{ type: "pauseRagIndexing" }')
    expect(source).toContain('{ type: "resumeRagIndexing" }')
    expect(source).toContain('{ type: "cancelRagIndexing" }')
    expect(source).toContain('{ type: "showCodeGraphStatus" }')
    expect(source).toContain('{ type: "refreshCodeIntelligence" }')
    expect(source).toContain('{ type: "openEvidence"; path: string; line?: number }')
    expect(source).toContain('{ type: "exportMarkdown"; scope?: ExportScope; filenameHint?: string }')
    expect(source).toContain('{ type: "cancelSend" }')
    expect(source).toContain('case "cancelSend"')
    expect(source).toContain("cancelActiveSend")
    expect(source).toContain("activeSendController")
    expect(source).toContain("sendMessageAsync({")
    expect(source).toContain("signal,")
    expect(source).toContain("showSaveDialog")
    expect(source).toContain("workspace.fs.writeFile")
    expect(source).toContain("parseExplicitExportCommand")
    expect(source).toContain("isExportIntentCandidate")
    expect(source).toContain("parseExportIntentResponse")
    expect(source).toContain("hiddenExportIntentSessions")
    expect(source).toContain('case "indexCodeGraph"')
    expect(source).toContain('case "rebuildCodeGraph"')
    expect(source).toContain('case "pauseCodeGraph"')
    expect(source).toContain('case "resumeCodeGraph"')
    expect(source).toContain('case "cancelCodeGraph"')
    expect(source).toContain('case "pauseRagIndexing"')
    expect(source).toContain('case "resumeRagIndexing"')
    expect(source).toContain('case "cancelRagIndexing"')
    expect(source).toContain('case "showCodeGraphStatus"')
    expect(source).toContain('case "refreshCodeIntelligence"')
    expect(source).toContain('case "openEvidence"')
    expect(source).toContain("indexWorkspace(force)")
    expect(source).toContain("showStatus()")
    expect(source).toContain("intelligenceSnapshot()")
    expect(source).toContain("if (this.loadingCodeIntelligence)")
    expect(source).toContain("private codeIntelligenceError")
    expect(source).toContain("codeIntelligenceError: this.codeIntelligenceError")
  })
})
