import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

describe("chat history flow", () => {
  const chatViewSource = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")
  const chatHtmlSource = readFileSync(join(import.meta.dir, "..", "src", "chat-html.ts"), "utf8")
  const chatStreamSource = readFileSync(join(import.meta.dir, "..", "src", "chat-stream.ts"), "utf8")

  test("posts sessions and loading state to the webview", () => {
    expect(chatViewSource).toContain("sessions: this.sessions")
    expect(chatViewSource).toContain("currentSessionID: this.sessionID")
    expect(chatViewSource).toContain("loadingMessages: this.loadingMessages")
  })

  test("loads messages when a session is selected", () => {
    expect(chatViewSource).toContain('{ type: "selectSession"; sessionID: string }')
    expect(chatViewSource).toContain("private async selectSession")
    expect(chatViewSource).toContain("await this.loadSessionMessages(client, sessionID)")
    expect(chatViewSource).toContain("client.getMessages(sessionID, SESSION_MESSAGE_LIMIT, signal)")
  })

  test("deletes chat history sessions after confirmation", () => {
    expect(chatViewSource).toContain('{ type: "deleteSession"; sessionID: string }')
    expect(chatViewSource).toContain("private async deleteSession")
    expect(chatViewSource).toContain('await this.deleteSession(message.sessionID)')
    expect(chatViewSource).toContain("vscode.window.showWarningMessage")
    expect(chatViewSource).toContain('client.deleteSession(sessionID, signal)')
    expect(chatViewSource).toContain("await this.refreshSessionList(client)")
    expect(chatViewSource).toContain("this.reconcileSessionSelection()")
    expect(chatHtmlSource).toContain('deleteButton.title = "Delete chat history"')
    expect(chatHtmlSource).toContain('deleteButton.setAttribute("aria-label", "Delete chat history")')
    expect(chatHtmlSource).toContain('vscode.postMessage({ type: "deleteSession", sessionID: session.id })')
  })

  test("refreshes session history after session-changing actions", () => {
    expect(chatViewSource).toContain("private async refreshSessionList")
    expect(chatViewSource).toContain("await this.refreshSessionList(client)")
    expect(chatViewSource).toContain("client.listSessions(signal)")
    expect(chatViewSource).toContain("this.isVisibleChatSession(session)")
    expect(chatViewSource).toContain("isPluginChatSession(session)")
  })

  test("hides inline completion sessions from chat history", () => {
    expect(chatViewSource).toContain("isInlineCompletionSession")
    expect(chatViewSource).toContain("hiddenCompletionSessions")
    expect(chatViewSource).toContain("if (isInlineCompletionSession(session)) return false")
  })

  test("hides persisted inline completion prompts when old sessions are selected", () => {
    expect(chatViewSource).toContain("messages.some(isInlineCompletionMessage)")
    expect(chatViewSource).toContain("private async hideCompletionSession")
    expect(chatViewSource).toContain("this.sessions = this.sessions.filter((session) => session.id !== sessionID)")
    expect(chatViewSource).toContain("this.reconcileSessionSelection()")
  })

  test("hides external ChipMate sessions from plugin chat history", () => {
    expect(chatViewSource).toContain("CHAT_SESSION_TITLE")
    expect(chatViewSource).toContain("hiddenExternalSessions")
    expect(chatViewSource).toContain("messages.some(isExternalChatMessage)")
    expect(chatViewSource).toContain("private async hideExternalSession")
    expect(chatViewSource).toContain("Hidden external ChipMate session")
  })

  test("recovers when the direct runtime has lost the selected session", () => {
    expect(chatViewSource).toContain("isSessionNotFoundError")
    expect(chatViewSource).toContain("private reconcileSessionSelection")
    expect(chatViewSource).toContain("this.sessions.some((session) => session.id === this.sessionID)")
    expect(chatViewSource).toContain("private async loadSelectedSessionMessages")
    expect(chatViewSource).toContain("private async recoverMissingSession")
  })

  test("retries sends with a new session after stale-session errors", () => {
    expect(chatViewSource).toContain("let preparedMessage")
    expect(chatViewSource).toContain("private async sendPreparedMessage")
    expect(chatViewSource).toContain("Selected ChipMate session was not found; retrying with a new session.")
    expect(chatViewSource).toContain("this.clearMissingSession(this.sessionID)")
  })

  test("waits for local code graph readiness before sending", () => {
    expect(chatViewSource).toContain("codeGraph: this.deps.codeGraph")
    expect(chatViewSource).toContain("private async waitForCodeGraphReady")
    expect(chatViewSource).toContain("await this.waitForCodeGraphReady(settings)")
    expect(chatViewSource).toContain("this.deps.codeGraph.waitForReady()")
    expect(chatViewSource).toContain("CodeGraphReadinessError")
    expect(chatViewSource).toContain("codeGraphWaitDetail")
    expect(chatViewSource).toContain("[codegraph] blocked send")
  })

  test("handles RAG settings actions from the webview without a separate API key path", () => {
    expect(chatViewSource).toContain('type: "saveRagSettings" | "testRagSettings"')
    expect(chatViewSource).not.toContain('type: "setRag' + 'ApiKey"')
    expect(chatViewSource).toContain("private async saveRagSettings")
    expect(chatViewSource).toContain("private async testRagSettings")
    expect(chatViewSource).not.toContain("private async setRag" + "ApiKey")
    expect(chatViewSource).toContain("await saveRagSettings(input)")
    expect(chatViewSource).toContain("ragSettingsInputChangesEmbeddingIdentity")
    expect(chatViewSource).toContain("ragSettingsInputMatchesCurrent(input")
    expect(chatViewSource).toContain("ragExistingIndexConfirmationReason")
    expect(chatViewSource).toContain("confirmForceRagRebuild")
    expect(chatViewSource).toContain("forceRebuild: true")
    expect(chatViewSource).toContain("preserveExistingIndex: true")
    expect(chatViewSource).toContain("RAG settings not saved. Existing local RAG index kept.")
    expect(chatViewSource).toContain("Embedding endpoint 或 model 已变化")
    expect(chatViewSource).toContain("本地已有完整 RAG 索引")
    expect(chatViewSource).toContain("本地已有未完成的 RAG 索引")
    expect(chatViewSource).toContain("this.deps.codeGraph?.testRagConfiguration()")
    expect(chatViewSource).toContain("[rag-test] testing RAG configuration")
    expect(chatViewSource).toContain("[rag-test] result:")
    expect(chatViewSource).not.toContain("this.deps.promptRag" + "ApiKey()")
    expect(chatViewSource).toContain('type: "ragStatus"')
    expect(chatViewSource).toContain('type: "pauseRagIndexing"')
    expect(chatViewSource).toContain('type: "resumeRagIndexing"')
    expect(chatViewSource).toContain('type: "cancelRagIndexing"')
    expect(chatViewSource).toContain("this.deps.codeGraph?.pauseRagIndexing")
    expect(chatViewSource).toContain("this.deps.codeGraph?.resumeRagIndexing")
    expect(chatViewSource).toContain("this.deps.codeGraph?.cancelRagIndexing")
  })

  test("keeps Document RAG status and controls independent from code RAG", () => {
    const contextSource = readFileSync(join(import.meta.dir, "..", "src", "context.ts"), "utf8")

    expect(chatViewSource).toContain("documentRag?: DocumentRagContextProvider")
    expect(chatViewSource).toContain("documentRag: this.deps.documentRag?.status()")
    expect(chatViewSource).toContain('case "pauseDocumentRagIndexing"')
    expect(chatViewSource).toContain('case "resumeDocumentRagIndexing"')
    expect(chatViewSource).toContain('case "rebuildDocumentRag"')
    expect(chatViewSource).toContain('case "showDocumentRagStatus"')
    expect(contextSource).toContain("documentRag?: DocumentRagContextProvider")
    expect(contextSource).toContain("retrieveDocumentRagEvidence")
    expect(contextSource).toContain("Local document RAG evidence")
    expect(contextSource).toContain("<local-document-rag>")
  })

  test("defaults the RAG rebuild confirmation to keeping the existing index", () => {
    const start = chatViewSource.indexOf("private async confirmForceRagRebuild")
    const end = chatViewSource.indexOf("private async testRagSettings", start)
    const body = chatViewSource.slice(start, end)
    const keep = 'const keep = { title: "否，保留现有索引" }'
    const force = 'const force = { title: "是，强制重建" }'

    expect(body.indexOf(keep)).toBeGreaterThanOrEqual(0)
    expect(body.indexOf(force)).toBeGreaterThan(body.indexOf(keep))
    expect(body).toContain("selected?.title === force.title")
    expect(body).not.toContain("isCloseAffordance")
  })

  test("streams chat replies through ChipMate events with async polling fallback", () => {
    expect(chatViewSource).toContain("ensureEventSubscription")
    expect(chatViewSource).toContain("subscribeEvents")
    expect(chatViewSource).toContain("sendMessageAsync")
    expect(chatViewSource).toContain("startMessagePollingFallback")
    expect(chatViewSource).toContain("pollActiveSendMessages")
    expect(chatViewSource).toContain("MESSAGE_POLL_INTERVAL_MS")
    expect(chatViewSource).toContain("EVENT_READY_TIMEOUT_MS")
    expect(chatViewSource).not.toContain("live stream unavailable; falling back to blocking message request")
    expect(chatViewSource).toContain("finishStreamingSession")
    expect(chatStreamSource).toContain('case "message.part.updated"')
    expect(chatStreamSource).toContain('case "message.part.delta"')
    expect(chatStreamSource).toContain('case "session.status"')
  })

  test("cancels active async sends through remote abort and suppresses late stream events", () => {
    expect(chatViewSource).toContain("SESSION_ABORT_TIMEOUT_MS")
    expect(chatViewSource).toContain("await this.cancelActiveSend()")
    expect(chatViewSource).toContain("client.abortSession(sessionID, signal)")
    expect(chatViewSource).toContain("this.beginActiveSend(client, sessionID)")
    expect(chatViewSource).toContain("this.startSendStatusWatchdog(client, sessionID, generation)")
    expect(chatViewSource).toContain("this.stopSendStatusWatchdog()")
    expect(chatViewSource).toContain("this.stopMessagePollingFallback()")
    expect(chatViewSource).toContain("suppressStreamingEventsForSession")
    expect(chatViewSource).toContain("shouldSuppressStreamingEvent")
    expect(chatViewSource).toContain("chipMateEventSessionID")
    expect(chatViewSource).toContain("sendCancellable:")
  })

  test("queues busy chat sends and drains them FIFO after terminal send states", () => {
    expect(chatViewSource).toContain("const MAX_QUEUED_CHAT_SENDS = 10")
    expect(chatViewSource).toContain("type QueuedChatSend")
    expect(chatViewSource).toContain("private queuedSends: QueuedChatSend[] = []")
    expect(chatViewSource).toContain("private enqueueChatSend")
    expect(chatViewSource).toContain("clientQueueID?: string")
    expect(chatViewSource).toContain("this.enqueueChatSend(text, options, mentioned.uris, mentioned.refs, clientQueueID, contextItems)")
    expect(chatViewSource).toContain('type: "queueUpdated"')
    expect(chatViewSource).toContain('type: "queueRejected"')
    expect(chatViewSource).toContain("private postQueueUpdated")
    expect(chatViewSource).toContain("private postQueueRejected")
    expect(chatViewSource).toContain("private async drainQueuedSends")
    expect(chatViewSource).toContain("const next = this.queuedSends.shift()")
    expect(chatViewSource).toContain("this.postQueueUpdated(this.queuedSends.length > 0")
    expect(chatViewSource).toContain("const mentioned = await this.resolveExistingMentionedFiles(next.mentionedFileRefs)")
    expect(chatViewSource).toContain("await this.processSendMessage(next.text, next.options, mentioned.uris, next.contextItems)")
    expect(chatViewSource).toContain("contextItems: LocalContextItem[]")
    expect(chatViewSource).toContain("void this.drainQueuedSends()")
    expect(chatViewSource).toContain("queuedSends: this.queuedSends.map")
    expect(chatViewSource).toContain("queuedSendCount: this.queuedSends.length")
    expect(chatViewSource).toContain("queuedSendLimit: MAX_QUEUED_CHAT_SENDS")
    expect(chatViewSource).not.toContain('localMessage("user", trimmed || "Please review the referenced files.", { queued: true })')
  })

  test("clears queued chat sends on session and client boundaries", () => {
    expect(chatViewSource).toContain("private clearQueuedSends")
    expect(chatViewSource).toContain("this.queuedSends = []")
    expect(chatViewSource).toContain('this.postQueueUpdated("")')
    expect(chatViewSource).toContain("setConnectionState(state: ConnectionState")
    expect(chatViewSource).toContain("this.clearQueuedSends()")
    expect(chatViewSource).toContain("private async connectWithSettings")
    expect(chatViewSource).toContain("private async selectSession")
    expect(chatViewSource).toContain("private async deleteSession")
    expect(chatViewSource).toContain("if (wasCurrent) this.clearQueuedSends()")
    expect(chatViewSource).toContain("private deleteQueuedSend")
    expect(chatViewSource).toContain("private editQueuedSend")
    expect(chatViewSource).toContain('type: "restoreQueuedSendDraft"')
  })

  test("recovers the composer from remote retry session statuses", () => {
    expect(chatViewSource).toContain("SEND_STATUS_POLL_INTERVAL_MS")
    expect(chatViewSource).toContain("client.getSessionStatuses(signal)")
    expect(chatViewSource).toContain("startSendStatusWatchdog")
    expect(chatViewSource).toContain("failActiveSendWithRetry")
    expect(chatViewSource).toContain('status?.type === "retry"')
    expect(chatViewSource).toContain("result.retry")
    expect(chatViewSource).toContain("remoteRetryMessage")
    expect(chatViewSource).toContain("this.clearActiveSendState()")
    expect(chatViewSource).toContain("this.sending = false")
    expect(chatViewSource).toContain("远端 ChipMate 正在重试模型请求")
    expect(chatStreamSource).toContain("retry?: ChipMateSessionStatus")
    expect(chatStreamSource).toContain('retry: type === "retry" ? normalizedStatus : undefined')
  })

  test("surfaces interrupted active sends from stream errors and status polling", () => {
    expect(chatViewSource).toContain("failActiveSendWithInterruption")
    expect(chatViewSource).toContain('status?.type === "error"')
    expect(chatViewSource).toContain("result.interruption")
    expect(chatViewSource).toContain("[send] interrupted")
    expect(chatViewSource).toContain("vscode.window.showWarningMessage")
    expect(chatViewSource).toContain("对话已中断")
    expect(chatStreamSource).toContain("interruption?: ChipMateSessionStatus")
    expect(chatStreamSource).toContain('type === "error" && status.interrupted === true')
  })

  test("renders markdown, code copy, and thinking state in the webview", () => {
    expect(chatHtmlSource).toContain("function renderMarkdownInto")
    expect(chatHtmlSource).toContain("function renderTextMarkdown")
    expect(chatHtmlSource).toContain("mdQuote")
    expect(chatHtmlSource).toContain("mdDivider")
    expect(chatHtmlSource).toContain('const tag = ordered ? "ol" : "ul"')
    expect(chatHtmlSource).toContain("document.createElement(tag)")
    expect(chatHtmlSource).toContain("function appendInlineMarkdown")
    expect(chatHtmlSource).toContain("mdStrong")
    expect(chatHtmlSource).toContain("mdEm")
    expect(chatHtmlSource).toContain("function detectTableBlock")
    expect(chatHtmlSource).toContain("function detectMarkdownTable")
    expect(chatHtmlSource).toContain("function detectDelimitedTable")
    expect(chatHtmlSource).toContain("function detectPlainAlignedTable")
    expect(chatHtmlSource).toContain("function detectKeyValueBlock")
    expect(chatHtmlSource).toContain("looksLikeMarkdownListRows")
    expect(chatHtmlSource).toContain("isMarkdownListMarkerCell")
    expect(chatHtmlSource).toContain("looksLikeMarkdownLabelRows")
    expect(chatHtmlSource).toContain("isMarkdownLabelCellSafe")
    expect(chatHtmlSource).toContain("String.fromCharCode(0xff1a)")
    expect(chatHtmlSource).toContain("function tableBlock")
    expect(chatHtmlSource).toContain("tableToolbar")
    expect(chatHtmlSource).toContain("tableScroll")
    expect(chatHtmlSource).toContain("copyTableMarkdown")
    expect(chatHtmlSource).toContain("copyTableCsv")
    expect(chatHtmlSource).toContain("toggleTableRaw")
    expect(chatHtmlSource).toContain("function tableToMarkdown")
    expect(chatHtmlSource).toContain("function tableToCsv")
    expect(chatHtmlSource).toContain("Raw table text")
    expect(chatHtmlSource).toContain("function codeBlock")
    expect(chatHtmlSource).toContain("codeLanguage")
    expect(chatHtmlSource).toContain("appendHighlightedCode")
    expect(chatHtmlSource).toContain("tokenizeCode")
    expect(chatHtmlSource).toContain("normalizeCodeLanguage")
    expect(chatHtmlSource).toContain("syntaxKeyword")
    expect(chatHtmlSource).toContain("syntaxString")
    expect(chatHtmlSource).toContain("syntaxComment")
    expect(chatHtmlSource).toContain("syntaxFunction")
    expect(chatHtmlSource).toContain("syntaxInserted")
    expect(chatHtmlSource).toContain("async function copyCode")
    expect(chatHtmlSource).toContain('setButtonTemporaryLabel(button, "Copied", previousLabel)')
    expect(chatHtmlSource).toContain('copy.className = "copyCode oc-icon-btn oc-liquid-btn"')
    expect(chatHtmlSource).toContain("function thinkingNode")
    expect(chatHtmlSource).toContain("hasAssistantContentAfterLastUser")
  })

  test("renders message actions and outline controls without nested long-answer scrolling", () => {
    expect(chatHtmlSource).toContain("function messageActions")
    expect(chatHtmlSource).toContain("copyAnswer")
    expect(chatHtmlSource).toContain("copyMarkdown")
    expect(chatHtmlSource).toContain("collapseMessage")
    expect(chatHtmlSource).toContain("jumpStructure")
    expect(chatHtmlSource).toContain("function toggleMessageCollapse")
    expect(chatHtmlSource).toContain("function messageOutline")
    expect(chatHtmlSource).toContain("messageOutlineSummary")
    expect(chatHtmlSource).not.toContain("function toggleLongMessage")
    expect(chatHtmlSource).not.toContain("messageLongHint")
    expect(chatHtmlSource).not.toContain("longAnswer")
    expect(chatHtmlSource).not.toContain("longExpanded")
    expect(chatHtmlSource).toContain("function scrollToNextMessageStructure")
    expect(chatHtmlSource).toContain("function markdownToPlainText")
    expect(chatHtmlSource).toContain('aria-expanded", options.isCollapsed ? "false" : "true"')
    expect(chatHtmlSource).toContain("function onPopupMenuKeydown")
    expect(chatHtmlSource).toContain("function focusPopupMenuItem")
    expect(chatHtmlSource).toContain('event.key === "ArrowDown"')
    expect(chatHtmlSource).toContain('event.key === "ArrowUp"')
    expect(chatHtmlSource).toContain("forced-colors: active")
    expect(chatHtmlSource).toContain('event.key !== "Escape"')
  })

  test("collapses the composer and context panel", () => {
    expect(chatHtmlSource).toContain('id="composerStatusBar"')
    expect(chatHtmlSource).toContain('id="composerStatusToggle"')
    expect(chatHtmlSource).not.toContain('id="panelStatusPill"')
    expect(chatHtmlSource).toContain('id="contextStatusPill"')
    expect(chatHtmlSource).toContain('id="indexStatusPill"')
    expect(chatHtmlSource).toContain('id="guardStatusPill"')
    expect(chatHtmlSource).toContain('id="usageStatusPill"')
    expect(chatHtmlSource).toContain('class="composerSupportRail" aria-label="Composer status details"')
    expect(chatHtmlSource).toContain('id="composerProgress" class="composerProgress" aria-hidden="true"')
    expect(chatHtmlSource).toContain("function renderComposerProgress")
    expect(chatHtmlSource).toContain("function contextUsageProgress")
    expect(chatHtmlSource).toContain('aria-controls="composerPanel"')
    expect(chatHtmlSource).toContain("composerToggleIcon")
    expect(chatHtmlSource).toContain("composerToggleFull")
    expect(chatHtmlSource).toContain("composerToggleShort")
    expect(chatHtmlSource).toContain("LIQUID_ICONS")
    expect(chatHtmlSource).toContain("STATUS_ICONS")
    expect(chatHtmlSource).toContain("appendLiquidIcon")
    expect(chatHtmlSource).toContain("renderStatusBadge")
    expect(chatHtmlSource).toContain("statusBadge")
    expect(chatHtmlSource).toContain("Hide input")
    expect(chatHtmlSource).toContain("Show input")
    expect(chatHtmlSource).toContain('setSendButtonContent(button, cancellable ? "stop" : "send", label, loading)')
    expect(chatHtmlSource).toContain("let composerCollapsed = false")
    expect(chatHtmlSource).toContain('let composerPinnedStatusPopover = ""')
    expect(chatHtmlSource).toContain('let composerHoverStatusPopover = ""')
    expect(chatHtmlSource).toContain("let composerHoverCloseTimer = 0")
    expect(chatHtmlSource).toContain("function toggleComposerPanel")
    expect(chatHtmlSource).toContain("function closeComposerPopups")
    expect(chatHtmlSource).toContain("function renderComposerStatusBar")
    expect(chatHtmlSource).toContain("function bindComposerStatusPill")
    expect(chatHtmlSource).toContain("function showComposerHoverPopover")
    expect(chatHtmlSource).toContain("function activeComposerStatusPopover")
    expect(chatHtmlSource).toContain("function toggleComposerStatusPopover")
    expect(chatHtmlSource).toContain("function renderComposerStatusPopover")
    expect(chatHtmlSource).toContain("function renderContextStatusPopover")
    expect(chatHtmlSource).toContain("function renderIndexStatusPopover")
    expect(chatHtmlSource).toContain("function renderGuardStatusPopover")
    expect(chatHtmlSource).toContain("function renderUsageStatusPopover")
    expect(chatHtmlSource).toContain("panel.hidden = composerCollapsed")
    expect(chatHtmlSource).toContain("composerWrap.collapsed")
    expect(chatHtmlSource).toContain('id="contextChips" class="contextChips"')
    expect(chatHtmlSource).toContain("function renderContextChips")
    expect(chatHtmlSource).toContain("Selection · ")
    expect(chatHtmlSource).toContain("Guard warning")
    expect(chatHtmlSource).not.toContain("compactRing")
    expect(chatHtmlSource).not.toContain("statusRing")
    expect(chatHtmlSource).toContain("function formatRingProgress")
    expect(chatHtmlSource).toContain("function indexStatusIconMarkup")
    expect(chatHtmlSource).toContain("function codeGraphStatusIconMarkup")
    expect(chatHtmlSource).toContain("function indexStatusIconHtml")
    expect(chatHtmlSource).toContain("function codeGraphStatusIconHtml")
    expect(chatHtmlSource).toContain('class="codegraph-status-glyph"')
    expect(chatHtmlSource).toContain('iconHtml: codeGraphStatusIconHtml(view.kind)')
    expect(chatHtmlSource).not.toContain('iconHtml: indexStatusIconHtml(view.kind, "type-hierarchy")')
    expect(chatHtmlSource).not.toContain('iconHtml: indexStatusIconHtml(view.kind, "graph")')
    expect(chatHtmlSource).toContain('iconHtml: indexStatusIconHtml(view.kind, "database")')
    expect(chatHtmlSource).toContain('iconHtml: indexStatusIconHtml(view.kind, "${documentRagStatusCodicon}", view.badgeKind)')
    expect(chatHtmlSource).not.toContain("function contextUsageRatio")
    const finalStatusBarRule = chatHtmlSource.slice(
      chatHtmlSource.lastIndexOf("    .composerStatusBar {"),
      chatHtmlSource.indexOf("    .composerWrap.collapsed", chatHtmlSource.lastIndexOf("    .composerStatusBar {")),
    )
    expect(finalStatusBarRule).toContain("position: static;")
    expect(finalStatusBarRule).toContain("justify-content: flex-start;")
    expect(finalStatusBarRule).not.toContain("position: absolute;")
    expect(finalStatusBarRule).not.toContain("justify-content: space-between;")
    expect(chatHtmlSource).toContain("--composer-icon-button-size: 28px;")
    expect(chatHtmlSource).toContain("--composer-toolbar-icon-slot-size: 22px;")
    expect(chatHtmlSource).toContain("--composer-toolbar-glyph-size: 17px;")
    expect(chatHtmlSource).toContain("--composer-toolbar-status-glyph-size: 13px;")
    expect(chatHtmlSource).toContain(".chat-toolbar-icon-button,")
    expect(chatHtmlSource).toContain(".chat-toolbar-icon-slot {")
    expect(chatHtmlSource).toContain(".index-status-icon {")
    expect(chatHtmlSource).toContain("color: var(--vscode-testing-iconPassed, #3fb950);")
    expect(chatHtmlSource).not.toContain("badgeText: count > 0")
    expect(chatHtmlSource).toContain('badgeText: ""')
    expect(chatHtmlSource).not.toContain("ringIcon:")
    expect(chatHtmlSource.indexOf('class="composerSupportRail" aria-label="Composer status details"')).toBeGreaterThan(
      chatHtmlSource.indexOf('id="composerStatusBar"'),
    )
    expect(chatHtmlSource.indexOf('class="composerSupportRail" aria-label="Composer status details"')).toBeLessThan(
      chatHtmlSource.indexOf('id="composerStatusPopover"'),
    )
    expect(chatHtmlSource).toContain('bindComposerStatusPill("contextStatusPill", "context", true)')
    expect(chatHtmlSource).toContain("color-mix(in srgb, currentColor")
    expect(chatHtmlSource).toContain("transform: none")
    expect(chatHtmlSource).toContain("composerStatusPill chat-toolbar-icon-button oc-icon-btn oc-liquid-btn context")
    expect(chatHtmlSource).toContain("composerStatusPill chat-toolbar-icon-button oc-icon-btn oc-liquid-btn index")
    expect(chatHtmlSource).toContain("composerStatusPill chat-toolbar-icon-button oc-icon-btn oc-liquid-btn guard ok")
    expect(chatHtmlSource).toContain("composerStatusPill chat-toolbar-icon-button oc-icon-btn oc-liquid-btn usage pending")
    expect(chatHtmlSource).toContain("icon: STATUS_ICONS.usage")
    expect(chatHtmlSource).not.toContain("ringIcon: STATUS_ICONS.usage")
    expect(chatHtmlSource).toContain("statusPopoverActions")
    expect(chatHtmlSource).toContain("contextRemoveButton")
    expect(chatHtmlSource).toContain('vscode.postMessage({ type: "removeContextItem"')
    expect(chatHtmlSource).toContain('vscode.postMessage({ type: "openContextItem"')
    expect(chatHtmlSource).not.toContain('<span class="pillText">Panel</span>')
    expect(chatHtmlSource).not.toContain('<span class="pillText">Ctx 0</span>')
    expect(chatHtmlSource).not.toContain('<span class="pillText">Guard ok</span>')
    expect(chatHtmlSource).not.toContain('id="guard"')
    expect(chatHtmlSource).not.toContain('id="usageMeter"')
    expect(chatHtmlSource).not.toContain('id="codeGraph"')
    expect(chatHtmlSource).not.toContain('id="chips"')
  })

  test("supports markdown export from explicit UI and model-classified prompts", () => {
    expect(chatHtmlSource).toContain('id="exportMarkdown"')
    expect(chatHtmlSource).toContain('class="composerActionRow toggles composerContextRail"')
    expect(chatHtmlSource).toContain('class="composerIconButton chat-toolbar-icon-button oc-icon-btn oc-liquid-btn"')
    expect(chatHtmlSource).toContain('id="composerMoreMenu" class="modelMenu composerMoreMenu"')
    expect(chatHtmlSource).toContain('class="modelMenuItem composerMoreItem"')
    expect(chatHtmlSource).toContain("function positionComposerMoreMenu")
    expect(chatHtmlSource).toContain('const trigger = el("composerMore");')
    expect(chatHtmlSource).toContain("const menuBottomY = Math.max(margin + 48, triggerRect.top - gap);")
    expect(chatHtmlSource).not.toContain('positionPopupMenu("composerMoreMenu", "composerMore", composerMoreMenuOpen)')
    expect(chatHtmlSource).toContain('aria-label="Export current chat to Markdown"')
    expect(chatHtmlSource).toContain('class="srOnly"')
    expect(chatHtmlSource).toContain("border: 0;")
    expect(chatHtmlSource).not.toContain("composerIconActions")
    expect(chatHtmlSource).toContain('type: "exportMarkdown", scope: "session"')
    expect(chatHtmlSource).toContain('event.data.type === "exportStatus"')
    expect(chatHtmlSource).toContain("looksLikeExportRequest")
    expect(chatViewSource).toContain('type: "exportMarkdown"')
    expect(chatViewSource).toContain("private async handleSendMessage")
    expect(chatViewSource).toContain("parseExplicitExportCommand(text)")
    expect(chatViewSource).toContain("isExportIntentCandidate(text)")
    expect(chatViewSource).toContain("buildExportIntentPrompt")
    expect(chatViewSource).toContain("parseExportIntentResponse(messageText(response))")
    expect(chatViewSource).toContain("private async exportMarkdown")
    expect(chatViewSource).toContain("formatChatExportMarkdown")
    expect(chatViewSource).toContain("showSaveDialog")
    expect(chatViewSource).toContain("workspace.fs.writeFile")
    expect(chatViewSource).toContain("EXPORT_INTENT_SESSION_TITLE")
    expect(chatViewSource).toContain("hiddenExportIntentSessions")
  })

  test("collapses reasoning content into a details card", () => {
    expect(chatViewSource).toContain("splitThinkingFromParts(message.parts)")
    expect(chatViewSource).toContain("if (split.reasoning || split.openThinking)")
    expect(chatViewSource).toContain('type: "reasoning"')
    expect(chatViewSource).toContain('title: "Thinking"')
    expect(chatViewSource).toContain('status: split.openThinking ? "running" : undefined')
    expect(chatViewSource).toContain("preview: split.preview")
    expect(chatViewSource).toContain("const rawText = split.text")
    expect(chatHtmlSource).toContain('const reasoningParts = parts.filter((part) => part.type === "reasoning");')
    expect(chatHtmlSource).toContain('root.appendChild(partCard(part, "Thinking", "reasoning"));')
    expect(chatHtmlSource).toContain('label.textContent = "Thinking...";')
    expect(chatHtmlSource).toContain('preview.className = "reasoningPreview";')
    expect(chatHtmlSource).toContain('details.className = "toolCard"')
    expect(chatHtmlSource).toContain('+ (part.status === "running" ? " is-running" : "");')
  })

  test("marks workspace filesystem tool usage", () => {
    expect(chatViewSource).toContain("WORKSPACE_FILESYSTEM_TOOLS")
    expect(chatViewSource).toContain("serverToolWarning")
    expect(chatViewSource).toContain("flaggedSessions")
    expect(chatHtmlSource).toContain("Workspace tools used")
  })

  test("normalizes legacy read tool names before rendering chat history", () => {
    expect(chatViewSource).toContain("function displayToolName(tool: string)")
    expect(chatViewSource).toContain('return tool === "chipmate_read_file" ? "chipmate_read" : tool')
    expect(chatViewSource).toContain('title: displayToolName("tool" in part && typeof part.tool === "string" ? part.tool : "tool")')
  })
})
