import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { createChatViewHtml, createNonce } from "../src/chat-html"

describe("chat webview html", () => {
  test("creates CSP-safe alphanumeric nonces", () => {
    for (let index = 0; index < 20; index++) {
      expect(createNonce()).toMatch(/^[A-Za-z0-9]{32}$/)
    }
  })

  test("uses the same nonce in CSP and script tag", () => {
    const html = createChatViewHtml("vscode-resource:", "AbC123")

    expect(html).toContain("script-src 'nonce-AbC123'")
    expect(html).toContain('<script nonce="AbC123">')
  })

  test("contains the webview script smoke-test markers", () => {
    const html = createChatViewHtml("vscode-resource:", "Smoke123")

    expect(html).toContain("acquireVsCodeApi()")
    expect(html).toContain('class="topbar"')
    expect(html).toContain('id="historyToggle"')
    expect(html).toContain('id="sessionList"')
    expect(html).toContain('id="messages"')
    expect(html).toContain("timelineItem")
    expect(html).toContain('class="composer"')
    expect(html).toContain('id="composerCollapseToggle"')
    expect(html).toContain('aria-controls="composerPanel"')
    expect(html).toContain('id="composerPanel"')
    expect(html).toContain("composerChevron")
    expect(html).toContain("composerCollapseSummary")
    expect(html).toContain("composerWrap.collapsed")
    expect(html).toContain("let composerCollapsed = false")
    expect(html).toContain("toggleComposerPanel")
    expect(html).toContain("renderComposerCollapse")
    expect(html).toContain("composerCollapseSummaryText")
    expect(html).toContain("closeComposerPopups")
    expect(html).toContain("panel.hidden = composerCollapsed")
    expect(html).toContain('button.setAttribute("aria-expanded"')
    expect(html).toContain("Expand input and context panel")
    expect(html).toContain("Collapse input and context panel")
    expect(html).toContain("Context ")
    expect(html).toContain("Guard warning")
    expect(html).toContain("modelMenuOpen = false")
    expect(html).toContain("agentMenuOpen = false")
    expect(html).toContain("mentionResults = []")
    expect(html).toContain('class="composerToolbar"')
    expect(html).toContain('id="composerHint"')
    expect(html).toContain('id="suggestions"')
    expect(html).toContain('id="send"')
    expect(html).toContain('id="exportMarkdown"')
    expect(html).toContain('type: "exportMarkdown", scope: "session"')
    expect(html).toContain('event.data.type === "exportStatus"')
    expect(html).toContain("looksLikeExportRequest")
    expect(html).toContain("localOnlyAgentBlocked() && !looksLikeExportRequest(text)")
    expect(html).toContain('id="guard"')
    expect(html).toContain('id="usageMeter"')
    expect(html).toContain("renderUsageMeter")
    expect(html).toContain("Usage pending")
    expect(html).toContain("messageUsage")
    expect(html).toContain("historyError")
    expect(html).toContain('id="codeGraph"')
    expect(html).toContain('id="codeIntelligence"')
    expect(html).toContain("renderCodeGraph")
    expect(html).toContain("renderCodeIntelligence")
    expect(html).toContain("let codeIntelligenceVisible = false")
    expect(html).toContain('let selectedStateMachineId = ""')
    expect(html).toContain("openOrRefreshCodeIntelligence")
    expect(html).toContain("requestCodeIntelligenceRefresh")
    expect(html).toContain('state.loadingCodeIntelligence = true')
    expect(html).toContain('textContent = state.loadingCodeIntelligence ? "Loading..." : "Refresh"')
    expect(html).toContain('data-code-intel-hide')
    expect(html).toContain('data-code-intel-refresh')
    expect(html).toContain('hide.textContent = "Hide"')
    expect(html).toContain('inspect.textContent = "Inspect"')
    expect(html).toContain('jump.textContent = "Source"')
    expect(html).toContain("Open source evidence: ")
    expect(html).toContain("Loading local code intelligence")
    expect(html).toContain("No code intelligence snapshot is loaded yet")
    expect(html).toContain("State Machine Audit")
    expect(html).toContain("Transition Table")
    expect(html).toContain("unknown from-state")
    expect(html).toContain("low confidence")
    expect(html).toContain("candidate")
    expect(html).toContain("codeIntelTransitionTable")
    expect(html).toContain("Index States")
    expect(html).toContain("Code graph disabled")
    expect(html).toContain("Waiting for code graph indexing")
    expect(html).toContain("Indexed: ")
    expect(html).toContain("Indexing...")
    expect(html).toContain("Code graph degraded")
    expect(html).toContain("Code graph paused")
    expect(html).toContain("Code graph rescan scheduled")
    expect(html).toContain("Code graph error")
    expect(html).toContain('data-code-graph-action')
    expect(html).toContain('message: "indexCodeGraph"')
    expect(html).toContain('message: "rebuildCodeGraph"')
    expect(html).toContain('message: "pauseCodeGraph"')
    expect(html).toContain('message: "resumeCodeGraph"')
    expect(html).toContain('message: "cancelCodeGraph"')
    expect(html).toContain('message: "showCodeGraphStatus"')
    expect(html).toContain('message: "refreshCodeIntelligence"')
    expect(html).toContain('type: "openEvidence"')
    expect(html).toContain('id="modelSelect"')
    expect(html).toContain('id="modelTrigger"')
    expect(html).toContain('id="modelMenu"')
    expect(html).toContain('id="refreshModels"')
    expect(html).toContain('id="manualModel"')
    expect(html).toContain('el("attach").addEventListener("click"')
    expect(html).toContain('el("connect").addEventListener("click"')
    expect(html).toContain('el("test").addEventListener("click"')
    expect(html).toContain('let pendingAction = ""')
    expect(html).toContain('pendingAction = type === "testWithSettings" ? "test" : "connect"')
    expect(html).toContain('type: "selectSession"')
    expect(html).toContain('type: "refreshSessions"')
    expect(html).toContain('type: "searchFilesForMention"')
    expect(html).toContain("onCodeGraphAction")
    expect(html).toContain("renderMarkdownInto")
    expect(html).toContain("--chat-user-font-size")
    expect(html).toContain(".timelineItem.assistant .messageBody")
    expect(html).toContain("mdQuote")
    expect(html).toContain("mdDivider")
    expect(html).toContain('const tag = ordered ? "ol" : "ul"')
    expect(html).toContain("document.createElement(tag)")
    expect(html).toContain("mdStrong")
    expect(html).toContain("mdEm")
    expect(html).toContain("nextInlineMarker")
    expect(html).toContain("findSingleStar")
    expect(html).toContain("codeLanguage")
    expect(html).toContain('copy.title = "Copy code block"')
    expect(html).toContain('button.textContent = "Copied"')
    expect(html).toContain("copyCode")
    expect(html).toContain("thinking")
    expect(html).toContain("prefers-reduced-motion")
    expect(html).toContain("history-closed history-narrow")
    expect(html).toContain("history-wide")
    expect(html).toContain("flex: 0 0 auto")
    expect(html).toContain("No current file captured")
    expect(html).toContain("autoContext")
    expect(html).toContain("Current: ")
    expect(html).toContain("mentionedFiles")
    expect(html).toContain("Local-only guard active")
    expect(html).toContain("guardSummary")
    expect(html).toContain("guardDetail")
    expect(html).toContain("VS Code agent: ")
    expect(html).toContain('id="agentTrigger"')
    expect(html).toContain('id="agentMenu"')
    expect(html).toContain("localOnlyAgentBlocked")
    expect(html).toContain("agentMatchesRequired")
    expect(html).toContain("canonicalAgentName")
    expect(html).toContain("Required VS Code local agent is unavailable")
    expect(html).toContain("Unavailable for VS Code local mode")
    expect(html).toContain("button.disabled = Boolean(disabled)")
    expect(html).toContain(".modelMenuItem.disabled")
    expect(html).toContain("Model: server default")
    expect(html).toContain("requestId")
    expect(html).toContain("Searching workspace files")
    expect(html).toContain("No files found")
    expect(html).toContain("Index truncated")
    expect(html).toContain("server filesystem tool used")
    expect(html).toContain('vscode.postMessage({ type: "ready" })')
    expect(html).toContain("OpenCode Remote UI loading")
  })

  test("does not auto-refresh when the webview resolves", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")
    const start = source.indexOf("resolveWebviewView")
    const end = source.indexOf("setConnectionState", start)
    const resolveBody = source.slice(start, end)

    expect(resolveBody).not.toContain("refresh()")
    expect(resolveBody).toContain("postState()")
  })

  test("chat provider handles code graph webview actions", () => {
    const source = readFileSync(join(import.meta.dir, "..", "src", "chat-view.ts"), "utf8")

    expect(source).toContain('{ type: "indexCodeGraph" }')
    expect(source).toContain('{ type: "rebuildCodeGraph" }')
    expect(source).toContain('{ type: "pauseCodeGraph" }')
    expect(source).toContain('{ type: "resumeCodeGraph" }')
    expect(source).toContain('{ type: "cancelCodeGraph" }')
    expect(source).toContain('{ type: "showCodeGraphStatus" }')
    expect(source).toContain('{ type: "refreshCodeIntelligence" }')
    expect(source).toContain('{ type: "openEvidence"; path: string; line?: number }')
    expect(source).toContain('{ type: "exportMarkdown"; scope?: ExportScope; filenameHint?: string }')
    expect(source).toContain('case "exportMarkdown"')
    expect(source).toContain("showSaveDialog")
    expect(source).toContain("workspace.fs.writeFile")
    expect(source).toContain("parseExplicitExportCommand")
    expect(source).toContain("isExportIntentCandidate")
    expect(source).toContain("parseExportIntentResponse")
    expect(source).toContain("hiddenExportIntentSessions")
    expect(source).toContain('case "indexCodeGraph"')
    expect(source).toContain('case "rebuildCodeGraph"')
    expect(source).toContain('case "pauseCodeGraph"')
    expect(source).toContain('case "resumeCodeGraph"')
    expect(source).toContain('case "cancelCodeGraph"')
    expect(source).toContain('case "showCodeGraphStatus"')
    expect(source).toContain('case "refreshCodeIntelligence"')
    expect(source).toContain('case "openEvidence"')
    expect(source).toContain("indexWorkspace(force)")
    expect(source).toContain("showStatus()")
    expect(source).toContain("intelligenceSnapshot()")
    expect(source).toContain("if (this.loadingCodeIntelligence)")
    expect(source).toContain("private codeIntelligenceError")
    expect(source).toContain("codeIntelligenceError: this.codeIntelligenceError")
  })
})
