import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

describe("code graph query observability", () => {
  const serviceSource = readFileSync(join(import.meta.dir, "..", "src", "codegraph-service.ts"), "utf8")
  const querySource = readFileSync(join(import.meta.dir, "..", "src", "codegraph-query.ts"), "utf8")
  const typesSource = readFileSync(join(import.meta.dir, "..", "src", "types.ts"), "utf8")

  test("logs query metrics to the output channel", () => {
    expect(serviceSource).toContain("[codegraph-query]")
    expect(serviceSource).toContain("formatCodeGraphQueryMetrics(context.metrics)")
    expect(serviceSource).toContain("candidates=")
    expect(serviceSource).toContain("elapsed=")
  })

  test("loads an existing index before auto-starting background indexing", () => {
    expect(serviceSource).toContain("async maybePromptAndIndex()")
    const start = serviceSource.indexOf("async maybePromptAndIndex()")
    const end = serviceSource.indexOf("async indexWorkspace", start)
    const body = serviceSource.slice(start, end)
    expect(body).toContain("await this.ensureIndexLoaded()")
    expect(body).toContain("if (this.status().state === \"ready\") return")
    expect(body).toContain("if (!settings.codeGraph.promptOnWorkspaceOpen) return")
    expect(body).toContain("void this.indexWorkspace(false)")
    expect(body.indexOf("await this.ensureIndexLoaded()")).toBeLessThan(body.indexOf("void this.indexWorkspace(false)"))
    expect(serviceSource).toContain("async waitForReady()")
    expect(serviceSource).toContain("private async runQueuedIndexJobs")
    expect(serviceSource).toContain("class WorkBudget")
  })

  test("status notifications do not block command completion", () => {
    const start = serviceSource.indexOf("async showStatus()")
    const end = serviceSource.indexOf("async refreshRagConfiguration", start)
    const body = serviceSource.slice(start, end)
    expect(body).toContain("void vscode.window.showInformationMessage")
    expect(body).not.toContain("await vscode.window.showInformationMessage")
  })

  test("keeps large indexes lazy-loadable and durable across job recovery", () => {
    expect(serviceSource).toContain("LARGE_INDEX_LAZY_FILE_THRESHOLD")
    expect(serviceSource).toContain("private async activeIndexForQuestion")
    expect(serviceSource).toContain("private async loadShardFiles")
    expect(serviceSource).toContain("private async saveJobCheckpoint")
    expect(serviceSource).toContain("checkpoint.json")
  })

  test("returns retrieval metrics with prompt context", () => {
    expect(querySource).toContain("metricsForResult(result")
    expect(querySource).toContain("candidateCount")
    expect(querySource).toContain("packedBytes")
    expect(querySource).toContain("elapsedMs")
  })

  test("separates lightweight RAG probes from vector index rebuilds", () => {
    expect(serviceSource).toContain("async testRagConfiguration()")
    expect(serviceSource).toContain("async refreshRagConfiguration()")
    expect(serviceSource).toContain("await this.testRagConfiguration()")
    expect(serviceSource).toContain("private async probeRagConfiguration()")
    expect(serviceSource).toContain("private async rebuildRagIndex")
    expect(serviceSource).toContain("async applyRagConfiguration(options")
    expect(serviceSource).toContain("ragProbeInFlight")
    expect(serviceSource).toContain("ragIndexInFlight")
    expect(serviceSource).toContain("pendingRagRefresh")
    expect(serviceSource).toContain("pendingRagRefreshIgnorePrevious")
    expect(serviceSource).toContain("pendingRagResumeTrigger")
    expect(serviceSource).toContain("private isCodeGraphReadyForRag()")
    expect(serviceSource).toContain("private suspendRagWorkForCodeGraphIndexing")
    expect(serviceSource).toContain("forceRebuild")
    expect(serviceSource).toContain("preserveExistingIndex")
    expect(serviceSource).toContain("this.abortRagIndex(\"RAG force rebuild requested\")")
    expect(serviceSource).toContain("await this.ragIndexInFlight")
    expect(serviceSource).toContain("private async clearStoredRagIndex")
    expect(serviceSource).toContain("vscode.workspace.fs.delete(this.ragDir(root), { recursive: true, useTrash: false })")
    expect(serviceSource).toContain("failed to clear stored RAG vector index before force rebuild")
    expect(serviceSource).toContain("private clearPendingRagWorkTimer")
    expect(serviceSource).toContain("this.ragIndex.sourceIndexUpdatedAt === this.index?.updatedAt")
    expect(serviceSource).toContain("runPendingRagRefreshWhenReady(\"RAG configuration changed\"")
    expect(serviceSource).toContain("status-refreshed")
    expect(serviceSource).toContain("ignorePrevious")
    expect(serviceSource).toContain("Waiting for local code graph indexing before RAG rebuild.")
    expect(serviceSource).toContain("availability: \"not-indexed\"")
    expect(serviceSource).toContain("availability: \"indexing\"")
    expect(serviceSource).toContain("private setAbortedRagIndexStatus")
    expect(serviceSource).toContain("this.setAbortedRagIndexStatus(policy.kind, rerankProbe, message)")
    expect(serviceSource).toContain("RAG vector index build was interrupted before vectors were saved")
    expect(serviceSource).toContain("[rag-index] embedding")
    expect(serviceSource).toContain("checkpointMode=${checkpointPlan.mode}")
    expect(serviceSource).toContain("chunks=${event.embeddedChunks}/${event.chunks}")
    expect(serviceSource).toContain("requestSec=${formatSeconds(event.elapsedMs)}")
	    expect(serviceSource).toContain("embeddingRequestSec=${formatSeconds(event.embeddingElapsedMs)}")
	    expect(serviceSource).toContain("continuePreviousElapsed")
	    expect(serviceSource).toContain("this.ragIndexCanContinueElapsed()")
	    expect(serviceSource).toContain("initialElapsedMs")
	    expect(serviceSource).toContain("indexElapsedMs")
	    expect(serviceSource).toContain("workerStatus")
	    expect(serviceSource).toContain("formatRagWorkerTelemetry")
	    expect(serviceSource).toContain("workers ${worker.activeWorkers}/${worker.maxWorkers}")
	    expect(serviceSource).toContain("buildElapsedMs")
	    expect(serviceSource).toContain("totalElapsedMs")
	    expect(typesSource).toContain('"checking" | "indexing"')
	    expect(typesSource).toContain("export type RagIndexProgress")
	    expect(typesSource).toContain("export type RagWorkerStatus")
	    expect(typesSource).toContain("indexElapsedMs?: number")
	  })

  test("marks code graph ready before scheduling dependent RAG rebuilds", () => {
    const fullStart = serviceSource.indexOf("private async runIndex")
    const fullEnd = serviceSource.indexOf("private startWatcher", fullStart)
    const fullBody = serviceSource.slice(fullStart, fullEnd)
    expect(fullBody.indexOf("this.setReadyStatus(\"Local C/C++ code graph is ready.\")")).toBeGreaterThan(-1)
    expect(fullBody.indexOf("this.suspendRagWorkForCodeGraphIndexing(\"full code graph indexing started\")")).toBeGreaterThan(-1)
    expect(fullBody.indexOf("this.scheduleRagRefreshAfterCodeGraphReady()")).toBeGreaterThan(-1)
    expect(fullBody.indexOf("this.setReadyStatus(\"Local C/C++ code graph is ready.\")")).toBeLessThan(fullBody.indexOf("this.scheduleRagRefreshAfterCodeGraphReady()"))

    const incrementalStart = serviceSource.indexOf("private async runIncrementalIndex")
    const incrementalEnd = serviceSource.indexOf("private async setEnabled", incrementalStart)
    const incrementalBody = serviceSource.slice(incrementalStart, incrementalEnd)
    expect(incrementalBody.indexOf("this.setReadyStatus(\"Local C/C++ code graph is ready after incremental update.\")")).toBeGreaterThan(-1)
    expect(incrementalBody.indexOf("this.suspendRagWorkForCodeGraphIndexing(\"incremental code graph indexing started\")")).toBeGreaterThan(-1)
    expect(incrementalBody.indexOf("this.scheduleRagRefreshAfterCodeGraphReady(changes.map")).toBeGreaterThan(-1)
    expect(incrementalBody.indexOf("this.setReadyStatus(\"Local C/C++ code graph is ready after incremental update.\")")).toBeLessThan(incrementalBody.indexOf("this.scheduleRagRefreshAfterCodeGraphReady(changes.map"))
  })

  test("rechecks pending RAG work after the code graph indexing queue is idle", () => {
    const helperStart = serviceSource.indexOf("private startQueuedIndexJobs")
    const helperEnd = serviceSource.indexOf("private async runIncrementalIndex", helperStart)
    const helperBody = serviceSource.slice(helperStart, helperEnd)
    expect(helperStart).toBeGreaterThan(-1)
    expect(helperBody).toContain("this.indexing = this.runQueuedIndexJobs().finally")
    expect(helperBody).toContain("this.schedulePendingRagWorkAfterCodeGraphReady(\"code graph indexing idle\")")
    expect(helperBody.indexOf("this.indexing = undefined")).toBeLessThan(helperBody.indexOf("this.schedulePendingRagWorkAfterCodeGraphReady(\"code graph indexing idle\")"))
    expect(serviceSource).toContain("return this.startQueuedIndexJobs()")
    expect(serviceSource).toContain("void this.startQueuedIndexJobs()")
    expect(serviceSource).toContain("const indexing = this.startQueuedIndexJobs()")
  })

  test("keeps pending RAG work scheduled when the ready notification races queue cleanup", () => {
    const schedulerStart = serviceSource.indexOf("private schedulePendingRagWorkAfterCodeGraphReady")
    const schedulerEnd = serviceSource.indexOf("private runPendingRagRefreshWhenReady", schedulerStart)
    const schedulerBody = serviceSource.slice(schedulerStart, schedulerEnd)
    expect(serviceSource).toContain("private pendingRagWorkTimer")
    expect(schedulerBody).toContain("this.clearPendingRagWorkTimer()")
    expect(schedulerBody).toContain("this.pendingRagWorkTimer = setTimeout")

    const runStart = serviceSource.indexOf("private runPendingRagRefreshWhenReady")
    const runEnd = serviceSource.indexOf("private isCodeGraphReadyForRag", runStart)
    const runBody = serviceSource.slice(runStart, runEnd)
    const notReadyStart = runBody.indexOf("if (!this.isCodeGraphReadyForRag())")
    expect(notReadyStart).toBeGreaterThan(-1)
    expect(runBody.indexOf("this.pendingRagRefresh = undefined")).toBeGreaterThan(notReadyStart)
    expect(runBody).toContain("this.schedulePendingRagWorkAfterCodeGraphReady(reason, RAG_PENDING_READY_RETRY_MS)")
    expect(runBody).toContain("[rag-index] waiting for code graph before rebuild reason=${reason}")
  })

  test("schedules automatic RAG index resume after recoverable pauses", () => {
    expect(serviceSource).toContain("private ragResumeTimer")
    expect(serviceSource).toContain("private ragResumeInFlight")
    expect(serviceSource).toContain("private schedulePendingRagWorkAfterCodeGraphReady")
    expect(serviceSource).toContain("private async scheduleRagIndexResumeFromStatus")
    expect(serviceSource).toContain("private async runRagIndexResume")
    expect(serviceSource).toContain("this.schedulePendingRagWorkAfterCodeGraphReady(\"code graph loaded\")")
    expect(serviceSource).toContain("this.pendingRagResumeTrigger = trigger")
    expect(serviceSource).toContain("auto resume deferred until code graph is ready")
    expect(serviceSource).toContain("reason !== \"request-budget\" && reason !== \"rate-limit\"")
    expect(serviceSource).toContain("[rag-index] resume scheduled")
    expect(serviceSource).toContain("[rag-index] auto resume starting")
    expect(serviceSource).toContain("resumeScheduledAt")
  })

  test("guards automatic RAG resume for stale cross-version partial indexes", () => {
    expect(serviceSource).toContain("ragManifestStaleReason")
    expect(serviceSource).toContain("loaded stale partial vector index; auto resume disabled")
    expect(serviceSource).toContain("index.state === \"stale\" || index.staleReason")
    expect(serviceSource).toContain("auto resume skipped reason=stale")
    expect(serviceSource).toContain("private ragIndexWithLifecycle")
    expect(serviceSource).toContain("this.extensionVersion()")
  })
})
