import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

describe("diagram generation prompts", () => {
  test("defaults common diagrams to Mermaid while keeping explicit draw.io routing", () => {
    const contextSource = readFileSync(join(import.meta.dir, "..", "src", "context.ts"), "utf8")
    const directClientSource = readFileSync(join(import.meta.dir, "..", "src", "direct-agent-client.ts"), "utf8")

    expect(contextSource).toContain("diagramOutputGuidance(input.settings.tools.enabled)")
    expect(contextSource).toContain("Diagram Output Routing Contract:")
    expect(contextSource).toContain("Use Mermaid as the default format")
    expect(contextSource).toContain("flowchart TD/LR")
    expect(contextSource).toContain("sequenceDiagram")
    expect(contextSource).toContain("stateDiagram-v2")
    expect(contextSource).toContain("Do not call draw.io tools for Mermaid output")
    expect(contextSource).toContain("Do not ask whether to use Mermaid or draw.io")
    expect(contextSource).toContain("Use draw.io/diagrams.net only when the user explicitly asks")
    expect(contextSource).toContain("chipmate_validate_diagram_ir")
    expect(contextSource).toContain("chipmate_create_drawio_diagram as the final renderer")
    expect(contextSource).toContain("Code evidence does not automatically mean code-flow")
    expect(contextSource).toContain("model/skill-authored visualPlan")
    expect(contextSource).toContain("mainBackbone.nodes/edges")
    expect(contextSource).toContain("edgePresentation edge-id map using mode line/rail/legend")
    expect(contextSource).toContain("rail as a scarce visual channel")
    expect(contextSource).toContain("at least as clear as a Mermaid baseline")
    expect(contextSource).toContain("The renderer does not infer main path")
    expect(contextSource).toContain("labels, function names, state names, Chinese words, or domain terms")
    expect(contextSource).toContain("composition.mode to single by default")
    expect(contextSource).toContain("Only set composition.mode to multi")
    expect(contextSource).toContain("always runs the Diagram Design Compiler before ELKJS layout")
    expect(contextSource).toContain("Active skills may refine evidence collection")
    expect(contextSource).toContain("VisualPlan hints")
    expect(contextSource).toContain("ChipMate tool calling is disabled")
    expect(contextSource).toContain("fenced `drawio` code block")
    expect(contextSource).toContain("<mxfile> or <mxGraphModel>")
    expect(contextSource).toContain("Do not reference external image URLs")
    expect(contextSource).not.toContain("Use Mermaid only when the user explicitly asks")
    expect(directClientSource).toContain("default to Mermaid")
    expect(directClientSource).toContain("Mermaid-default diagram requests")
    expect(directClientSource).toContain("For explicit complex draw.io requests")
    expect(directClientSource).toContain("use an evidence-backed DiagramIR workflow")
    expect(directClientSource).toContain("The model or active skill decides the user-visible diagramType")
    expect(directClientSource).toContain("Code evidence does not automatically mean code-flow")
    expect(directClientSource).toContain("all semantic presentation decisions")
    expect(directClientSource).toContain("include visualPlan with layoutProfile")
    expect(directClientSource).toContain("mainBackbone.nodes/edges")
    expect(directClientSource).toContain("edgePresentation edge-id map using mode line/rail/legend")
    expect(directClientSource).toContain("rail as a scarce visual channel")
    expect(directClientSource).toContain("at least as clear as a Mermaid baseline")
    expect(directClientSource).toContain("does not infer main path, exception path, business meaning, or importance")
    expect(directClientSource).toContain("call chipmate_validate_diagram_ir")
    expect(directClientSource).toContain("must not bypass the Design Compiler, ELKJS layout")
    expect(directClientSource).toContain("Diagram skill precedence")
    expect(directClientSource).toContain("VisualPlan hints")
    expect(directClientSource).toContain("composition.mode to single by default")
    expect(directClientSource).toContain("composition.mode to multi")
    expect(directClientSource).toContain("Do not handwrite mxCell/mxGeometry XML")
    expect(directClientSource).toContain("tool calling is disabled")
    expect(directClientSource).toContain("Do not reference external image/font/style URLs")
    expect(directClientSource).not.toContain("Use Mermaid only when the user explicitly asks")
  })
})
