import { formatAllowedInsertionAnchors } from "./commentAnchors"
import type { CommentGenerationContext } from "./commentTypes"

export function buildCommentPrompt(context: CommentGenerationContext) {
  const reviewScopeLabel = context.source === "currentFunction" ? "当前函数" : "用户选区"
  const modeSpecificInstructions = context.retrievalMode === "tool-driven"
    ? [
      "你已经拥有由模型主动调用本地只读 ChipMate 工具得到的仓库证据。",
      "工具证据可能来自 chipmate_read、文本搜索、CodeGraph、Document RAG 或 evidence 扩展读取。",
      "必须把工具证据与选区代码共同作为 grounding；不要因为 evidence 来自工具循环而降低可信度。",
      ...(context.outputDirective === "encourage-1-3"
        ? [
          `当前工具证据已经支撑高价值注释候选，最多返回 ${context.proposalBudget} 条。`,
          "除非所有可能注释都只是复述语法，或必须凭空猜测意图，否则不要返回空 proposals 数组。",
          "优先返回有证据支撑、绑定 codeEvidence 的中文注释。",
        ]
        : [
          "当工具证据不能明确支撑非显然注释时，返回空 proposals 数组。",
        ]),
    ]
    : context.retrievalMode === "graph-only"
    ? [
      "你已经拥有覆盖仓库的、有根据的 CodeGraph 结构证据。",
      "graph-only 模式仍然提供仓库级结构理解。",
      "当 CodeGraph 证据已经揭示代码目的时，不要因为没有 RAG 证据就默认放弃生成注释。",
      ...(context.outputDirective === "encourage-1-3"
        ? [
          `当前选区已经有足够的 CodeGraph 证据支撑高价值注释候选，最多返回 ${context.proposalBudget} 条。`,
          "除非所有可能注释都只是复述语法，或必须凭空猜测意图，否则不要返回空 proposals 数组。",
          "优先返回至少一条简洁、有证据支撑、锚定 direct refs 的中文注释。",
          "鼓励对象是 primary anchor 与内部高价值 anchors，而不是泛化多生成。",
        ]
        : [
          "当 CodeGraph 证据不能明确支撑非显然注释时，返回空 proposals 数组。",
        ]),
    ]
    : [
      "你同时拥有仓库 CodeGraph 结构证据和 RAG 语义证据。",
      "请把 graph 与 RAG evidence sections 作为并列 grounding sources 综合判断。",
      "优先选择由任一证据区或两个证据区共同支撑的最强中文解释。",
      ...(context.outputDirective === "encourage-1-3"
        ? [
          `当前 graph/RAG evidence 已经具备 direct refs 和至少 medium grounding，鼓励返回有证据支撑的注释候选，最多 ${context.proposalBudget} 条。`,
          "鼓励对象是 primary anchor 与内部高价值 anchors，而不是泛化多生成。",
        ]
        : []),
      "如果 graph 与 RAG 证据冲突或仍然无法得出结论，返回 {\"proposals\":[]}。",
    ]
  const selectionStrategyInstructions = context.selectionIntent === "functionOrBlockSummary"
    ? [
      `当前审阅范围是${reviewScopeLabel}，看起来是较长的函数或结构块。`,
      ...(context.source === "currentFunction"
        ? [
          "当前函数模式只是把光标所在函数解析成内部 selected range；不要扩展到 current file、相邻函数或目录级范围。",
          "优先函数入口注释，同时覆盖内部高价值逻辑，不逐行解释。",
        ]
        : []),
      `primaryAnchorPolicy=${context.primaryAnchorPolicy}`,
      `proposalBudget=${context.proposalBudget}`,
      `primaryAnchorLine=${context.primaryAnchorLine ?? "none"} 是函数或结构块入口候选；当 primaryAnchorPolicy=required-when-supported 且 evidence 支持时，默认返回 1 条整体/入口/函数级或块级中文注释。`,
      "只有当入口注释只能写成泛泛复述、无法绑定具体 codeEvidence 或必须猜测意图时，才可以省略 primary anchor。",
      `internalAnchorLines=${JSON.stringify(context.internalAnchorLines)} 是内部结构锚点；凡是有独立非显然语义、控制流含义、状态迁移、错误恢复、并发/ownership、DMA/cache 或硬件顺序约束的内部锚点，都可以生成候选，直到达到 proposalBudget。`,
      "不要把策略误解为只生成函数总注释；内部关键错误处理、状态迁移、并发/ownership、DMA/cache 或硬件顺序约束仍应被注释。",
      "也不要为了覆盖锚点或填满 proposalBudget 而凑数量；没有独立意义的内部锚点不要生成注释。",
      "如果内部注释比整体注释更有价值，可以只返回内部高价值锚点的 proposal，但不要因为存在内部高价值锚点就默认跳过有证据支撑的 primary anchor。",
    ]
    : [
      `当前审阅范围是${reviewScopeLabel}，更像局部代码块。`,
      "只在局部结构锚点存在非显然语义时生成注释，不强制生成整体/函数级注释。",
    ]
  return [
    "你是一个保守的固件代码注释助手。",
    "",
    `你的任务是为${reviewScopeLabel}中的 C/C++ 代码提出有价值的中文注释候选。`,
    "每条候选都必须把综合原因绑定到具体代码证据行段。",
    "",
    "不要重写代码。",
    "不要返回完整源码。",
    "不要编造硬件行为、协议含义、寄存器含义、业务规则或隐藏意图。",
    "如果意图不清楚，不要生成注释。",
    "必须使用仓库 evidence sections 作为依据。",
    "只有在证据支撑时才提出注释。",
    ...modeSpecificInstructions,
    ...selectionStrategyInstructions,
    ...(context.outputDirective === "allow-empty"
      ? ["如果仓库证据仍然较弱、缺失或无法得出结论，返回 {\"proposals\":[]}。"]
      : ["如果审阅 provided grounded refs and summaries 后仓库证据仍然较弱、缺失或无法得出结论，返回 {\"proposals\":[]}。"]),
    "",
    "只在注释能解释以下内容时生成：",
    "- 这段代码为什么存在",
    "- 硬件顺序约束",
    "- DMA/cache 一致性约束",
    "- 状态机迁移",
    "- 错误恢复和回滚行为",
    "- 队列 ownership 或并发约束",
    "- 非显然的固件行为",
    "- 非显然的协议行为",
    "",
    "不要生成只是复述语法的注释。",
    "",
    "不好的注释示例：",
    "- \"递增 i\"",
    "- \"检查 pointer 是否为 NULL\"",
    "- \"返回 result\"",
    "- \"遍历 array\"",
    "- \"设置 variable\"",
    "",
    "只返回严格 JSON。",
    "第一个可见输出字符必须是 {。",
    "不要使用 markdown code fence。",
    "不要在 JSON 外添加解释性文本。",
    "不要输出思考过程、自我检查、验证步骤、checklist 或对 JSON 是否有效的说明。",
    "不要解释为什么你的输出符合要求。",
    "",
    "中文输出要求：",
    "- commentText 必须使用简体中文自然语言编写，但要保留合法 C/C++ 注释语法。",
    "- functionHeader 的 commentText 必须描述函数职责、关键约束或整体流程，不要把函数签名、伪代码、独立 if/return/assignment 行放进注释正文。",
    "- 可以保留函数名、参数名和控制条件原文，但它们必须嵌入中文说明句子中，不要单独成为一行代码。",
    "- reason 必须使用简体中文。",
    "- codeEvidence 内的 anchorLabel、codeSummary、meaning 必须使用简体中文，代码标识符保持原文。",
    "- 函数名、变量名、宏名、寄存器名、协议名、硬件缩写、路径和 API 名称必须保持原文，不要翻译。",
    "- JSON 字段名、kind 枚举值和 confidence 枚举值必须保持下方 schema 指定的英文。",
    "",
    "Schema:",
    "{",
    "  \"proposals\": [",
    "    {",
    "      \"kind\": \"functionHeader\" | \"logicBlock\" | \"hardware\" | \"stateMachine\" | \"errorHandling\" | \"concurrency\" | \"dmaCache\" | \"other\",",
    "      \"insertBeforeLine\": number,",
    "      \"indent\": string,",
    "      \"commentText\": string,",
    "      \"anchor\": {",
    "        \"targetLineText\": string",
    "      },",
    "      \"confidence\": \"high\" | \"medium\" | \"low\",",
    "      \"reason\": string,",
    "      \"codeEvidence\": [",
    "        {",
    "          \"source\": \"selection\" | \"repository\",",
    "          \"filePath\": string,",
    "          \"startLine\": number,",
    "          \"endLine\": number,",
    "          \"anchorLabel\": string,",
    "          \"codeSummary\": string,",
    "          \"meaning\": string",
    "        }",
    "      ]",
    "    }",
    "  ]",
    "}",
    "",
    "规则：",
    "- insertBeforeLine 是 0-based，且必须指向 selected range 内的行。",
    "- commentText 只能是合法 C/C++ 注释文本。",
    "- 短逻辑注释使用 //。",
    "- 只有函数头注释才使用 /** ... */。",
    "- 注释要简洁。",
    "- 宁可返回少量高价值注释，不要返回大量显而易见的注释。",
    `- 全部模式最多返回 ${context.proposalBudget} 条 proposals。`,
    "- 每条 proposal 的 codeEvidence 必须是非空数组，最多 3 条。",
    "- 每条 proposal 必须至少包含 1 条 source=\"selection\" 的 codeEvidence，且 startLine/endLine 必须落在 selected range 内。",
    "- repository codeEvidence 只能作为补充，不能替代 selection codeEvidence。",
    "- codeEvidence.startLine 和 codeEvidence.endLine 都是 0-based inclusive 行号。",
    "- codeEvidence.anchorLabel 应是结构标签，例如 function、if、switch、error path、rollback path、state transition、ownership guard。",
    "- codeEvidence.codeSummary 要说明对应行段的代码写了什么。",
    "- codeEvidence.meaning 要说明这段代码代表什么、为什么重要、它如何支撑 commentText。",
    "- 如果无法把注释绑定到 selected range 内的具体行段，不要生成该 proposal。",
    "- insertBeforeLine 必须从 Allowed insertion anchors（允许插入锚点）列表中选择。",
    "- 必须逐字复制 Allowed insertion anchors 里的 insertBeforeLine 数值；不要根据 VS Code 显示行号、上下文位置或自然语言自行推算行号。",
    "- anchor.targetLineText 应对应你选择的 allowed anchor 的 targetLineText。",
    "- 禁止逐行解释代码，禁止为每一行代码生成注释。",
    "- 禁止在普通赋值语句或普通函数调用语句前连续插入注释，除非该行是允许插入锚点。",
    ...(context.retrievalMode === "graph-only"
      ? [`- graph-only 模式最多返回 ${context.proposalBudget} 条 proposals。`]
      : context.retrievalMode === "tool-driven"
        ? [`- tool-driven 模式最多返回 ${context.proposalBudget} 条 proposals。`]
      : []),
    "- 如果没有有价值的注释可添加，返回 {\"proposals\":[]}。",
    "",
    "文件路径：",
    context.filePath,
    "",
    "语言：",
    context.languageId,
    "",
    "Review scope:",
    context.source,
    "",
    "已有注释风格样例：",
    context.existingCommentExamples,
    "",
    "仓库证据检索模式：",
    context.retrievalMode,
    "",
    "注释生成指令：",
    context.outputDirective,
    "",
    "选区注释策略：",
    `selectionIntent=${context.selectionIntent}`,
    `proposalBudget=${context.proposalBudget}`,
    `primaryAnchorPolicy=${context.primaryAnchorPolicy}`,
    `primaryAnchorLine=${context.primaryAnchorLine ?? "none"}`,
    `primaryAnchorKind=${context.primaryAnchorKind ?? "none"}`,
    `internalAnchorLines=${JSON.stringify(context.internalAnchorLines)}`,
    "",
    "证据置信度：",
    context.groundingConfidence,
    "",
    "证据是否已为注释生成压缩：",
    context.evidenceCompacted ? "true" : "false",
    "",
    "仓库证据条目数：",
    String(context.evidenceItemCount),
    "",
    "Allowed insertion anchors（允许插入锚点）：",
    "下面是唯一允许使用的插入位置。insertBeforeLine 是 0-based，vscodeDisplayLine 仅用于人类阅读；输出 JSON 时只能使用 insertBeforeLine。",
    formatAllowedInsertionAnchors(context.allowedInsertionAnchors),
    "",
    "选区锚点证据：",
    context.evidenceSections.selectionAnchors,
    "",
    "CodeGraph 仓库摘要：",
    context.evidenceSections.graphRepoSummary,
    "",
    "CodeGraph 直接引用：",
    context.evidenceSections.graphDirectRefs,
    "",
    "RAG 语义摘要：",
    context.evidenceSections.ragSummary || "无。",
    "",
    "模型工具检索证据：",
    context.evidenceSections.toolEvidence || "无。",
    "",
    "证据结论摘要：",
    context.groundingSummary || context.evidenceSections.groundingSummary,
    "",
    "选区前代码：",
    context.contextBefore,
    "",
    "选中代码：",
    context.selectedCode,
    "",
    "选区后代码：",
    context.contextAfter,
  ].join("\n")
}
