export type Severity = "P0" | "P1" | "P2" | "P3"
export type AutomationKind = "automated" | "observe" | "planned"
export type RunMode = "real-profile-observe" | "cloned-profile-full" | "fixture-clean-room"

export type SystemCase = {
  id: string
  area: string
  title: string
  severity: Severity
  automation: AutomationKind
  modes: RunMode[]
  entrypoints: string[]
  userAction: string
  expected: string
  boundaries: string[]
  allowedFailures: string[]
  evidence: string[]
  commandId?: string
  fixture?: string
  destructive?: boolean
}

const commonEvidence = ["summary.json", "functional-checks.json", "logs/", "screenshots/"]

export const systemCases: SystemCase[] = [
  c("startup.extension-installed", "startup", "Installed ChipMate extension is discoverable", "P0", "observe", ["real-profile-observe", "cloned-profile-full", "fixture-clean-room"], ["extension:local.chipmate"], "List installed VS Code extensions.", "local.chipmate is installed with a concrete version.", ["extension absent", "multiple VS Code installations"], ["extension-missing"], ["installed-extensions.txt", "environment.json"]),
  c("startup.activate-chat", "startup", "ChipMate chat surface opens", "P0", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.openChat"], "Run Open ChipMate Chat.", "The command is accepted and activation logs are collected without startup runtime failures.", ["empty workspace", "single file window"], ["ui-automation-failure", "extension-host-error"], commonEvidence, "chipmate.openChat"),
  c("startup.activity-bar", "startup", "Activity bar container and sidebar are reachable", "P1", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:workbench.view.extension.chipmate"], "Open the ChipMate activity bar container.", "The target VS Code window remains usable and screenshots are captured.", ["narrow window", "dark theme"], ["ui-automation-failure"], commonEvidence, "workbench.view.extension.chipmate"),
  c("startup.output-open", "startup", "ChipMate Output channel opens", "P1", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.openOutput"], "Run Open ChipMate Output.", "Output can be opened and logs are collected.", ["no previous output", "fresh activation"], ["ui-automation-failure"], commonEvidence, "chipmate.openOutput"),
  c("startup.reload-window", "lifecycle", "Reload window preserves extension usability", "P1", "planned", ["cloned-profile-full"], ["command:workbench.action.reloadWindow"], "Reload VS Code and reopen ChipMate.", "ChipMate reactivates and prior storage remains readable.", ["extension host restart", "stale global state"], ["ui-automation-failure", "extension-host-error"], commonEvidence),
  c("startup.command-palette-sweep", "startup", "All public non-completion commands are inventoried and smokeable", "P1", "planned", ["cloned-profile-full"], ["command:chipmate.askSelection", "command:chipmate.askCurrentFile", "command:chipmate.designDoc.generate", "command:chipmate.provider.setApiKey", "command:chipmate.codeGraph.benchmark"], "Run command-palette sweep for public commands with safe fixtures.", "Commands either complete, show expected prompts, or report clear missing-context/provider reasons.", ["commands requiring prompt input", "commands requiring active selection"], ["ui-automation-failure", "configuration-error", "provider-error"], commonEvidence),
  c("provider.configured", "provider", "Configured provider is visible without leaking secrets", "P0", "observe", ["real-profile-observe", "cloned-profile-full"], ["setting:chipmate.provider.apiBaseUrl", "setting:chipmate.provider.chatModel"], "Read effective non-secret provider settings.", "Reports show configured/non-configured state but never raw API keys.", ["empty setting", "SecretStorage only"], ["configuration-error"], ["environment.json", "redaction-report.json"]),
  c("provider.missing", "provider", "Missing provider gives clear error", "P1", "planned", ["fixture-clean-room"], ["command:chipmate.newSession"], "Start a session with no provider configuration.", "User sees a clear configuration error, not a generic crash.", ["no API key", "no base URL"], ["configuration-error"], commonEvidence),
  c("provider.bad-url", "provider", "Bad provider URL is classified as transport error", "P1", "planned", ["cloned-profile-full"], ["setting:chipmate.provider.apiBaseUrl"], "Set provider URL to an invalid local endpoint and send chat.", "Failure is reported as provider/transport failure and does not poison RAG state.", ["DNS failure", "connection refused", "HTML response"], ["transport-error", "provider-error"], commonEvidence),
  c("provider.http-errors", "provider", "Provider HTTP failures are classified", "P1", "planned", ["cloned-profile-full"], ["setting:chipmate.provider.apiBaseUrl"], "Use mock provider responses 401/403/429/503.", "Each failure is classified and redacted.", ["rate limit", "unauthorized", "retry-after"], ["provider-error", "rate-limit"], commonEvidence),
  c("settings.provider-tuning", "settings", "Provider tuning settings are covered by boundary cases", "P2", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.provider."], "Vary provider token, temperature, topP, and context-length settings.", "Settings are validated, hot-refreshed, and failures remain provider-specific.", ["zero values", "large context", "invalid ranges"], ["configuration-error", "provider-error"], commonEvidence),
  c("settings.context", "settings", "Context settings are covered by boundary cases", "P2", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.context."], "Vary context limits, diagnostics, git diff, local-only, history, and memory-summary settings.", "Context packing and local-only behavior remain bounded and observable.", ["large files", "many files", "history overflow"], ["context-limit", "configuration-error"], commonEvidence),
  c("settings.permissions-tools-skills", "settings", "Permissions, tools, and skills settings are covered", "P1", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.permissions.", "setting-prefix:chipmate.tools.", "setting-prefix:chipmate.skills."], "Vary permission mode and tool/skill enablement settings.", "Tool/skill failures are classified and permission denials are explicit.", ["disabled tools", "missing skill", "denied command"], ["tool-error", "configuration-error"], commonEvidence),
  c("settings.mcp", "settings", "MCP settings are covered", "P2", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.mcp."], "Enable and disable MCP integration settings.", "MCP-disabled and MCP-error states are explicit and do not block core chat UI.", ["disabled MCP", "bad server config"], ["configuration-error", "tool-error"], commonEvidence),
  c("settings.word-updates", "settings", "Word render and update settings are covered", "P2", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.wordRender.", "setting-prefix:chipmate.updates."], "Vary render endpoint and update-check settings.", "Render/update failures are isolated from chat/RAG and have clear errors.", ["bad endpoint", "oversized update", "offline"], ["configuration-error", "transport-error"], commonEvidence),
  c("chat.new-session", "chat", "New session command reaches session lifecycle", "P1", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.newSession"], "Run New ChipMate Session.", "Command completes or reports a clear connection/configuration reason.", ["offline", "provider unavailable"], ["configuration-error", "provider-error"], commonEvidence, "chipmate.newSession"),
  c("chat.send-short", "chat", "Short chat request succeeds or fails clearly", "P1", "planned", ["cloned-profile-full"], ["webview:chat-input"], "Send a short prompt from the chat webview.", "Response streams to completion or records a clear provider error.", ["slow provider", "stream interrupted"], ["provider-error", "transport-error"], commonEvidence),
  c("chat.cancel-retry", "chat", "Cancel and retry are stable", "P2", "planned", ["cloned-profile-full"], ["webview:cancel", "webview:retry"], "Cancel an in-flight answer and retry.", "UI returns to a usable state and logs the cancellation.", ["provider slow", "double click"], ["provider-error", "ui-automation-failure"], commonEvidence),
  c("chat.long-context", "chat", "Long context is bounded and explained", "P1", "planned", ["cloned-profile-full"], ["webview:chat-input"], "Send a long prompt with attached files.", "Context packing is bounded and over-limit messages are clear.", ["very long prompt", "large attached file"], ["context-limit", "provider-error"], commonEvidence),
  c("context.add-file", "context", "Add current file to context", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.addFileToContext"], "Open a source file and add it to ChipMate context.", "Context command succeeds or reports a clear file-state reason.", ["path with spaces", "deleted file"], ["workspace-unsupported"], commonEvidence, "chipmate.addFileToContext", "edge-paths"),
  c("context.add-selection", "context", "Add selection to context", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.addSelectionToContext"], "Select text in a source file and add it to context.", "Selection is accepted; empty selection reports a warning.", ["empty selection", "large selection"], ["workspace-unsupported"], commonEvidence, "chipmate.addSelectionToContext", "small-c"),
  c("context.clear", "context", "Clear context resets visible state", "P2", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.clearContext"], "Run Clear ChipMate Context.", "Context state is cleared without errors.", ["already empty", "after file attach"], ["ui-automation-failure"], commonEvidence, "chipmate.clearContext"),
  c("context.mention-files", "mention", "File and symbol mentions resolve", "P2", "planned", ["cloned-profile-full"], ["webview:mention"], "Use @ mention for files and symbols.", "Matches appear, duplicate/no-match states are clear.", ["no match", "many matches", "Chinese path"], ["ui-automation-failure"], commonEvidence),
  c("codegraph.status", "codegraph", "CodeGraph status command reports state", "P1", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.codeGraph.status"], "Run Show Local Code Graph Status.", "Status command is accepted and storage/log summaries are collected.", ["not indexed", "ready", "stale"], ["index-stale", "workspace-unsupported"], commonEvidence, "chipmate.codeGraph.status"),
  c("codegraph.index", "codegraph", "CodeGraph index produces evidence", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.codeGraph.index"], "Run Index Local Code Graph on small C fixture.", "Logs or storage summary show scan/index/status evidence.", ["empty repo", "small C repo"], ["index-paused", "workspace-unsupported"], ["logs/", "codegraph-summary.json", "globalStorage-summary.json"], "chipmate.codeGraph.index", "small-c"),
  c("codegraph.rebuild", "codegraph", "CodeGraph rebuild from zero is observable", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.codeGraph.rebuild"], "Run Rebuild Local Code Graph.", "Rebuild logs are collected and storage summary changes are visible.", ["existing index", "no previous index"], ["index-paused", "extension-host-error"], ["logs/", "codegraph-summary.json", "globalStorage-summary.json"], "chipmate.codeGraph.rebuild", "small-c", true),
  c("codegraph.pause-resume", "codegraph", "CodeGraph pause and resume commands are stable", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.codeGraph.pause", "command:chipmate.codeGraph.resume"], "Pause then resume CodeGraph indexing.", "Both commands are accepted and do not leave the extension unusable.", ["not currently indexing", "already paused"], ["index-paused"], commonEvidence, "chipmate.codeGraph.pause"),
  c("codegraph.cancel", "codegraph", "CodeGraph cancel is recoverable", "P2", "automated", ["cloned-profile-full"], ["command:chipmate.codeGraph.cancel"], "Cancel CodeGraph indexing.", "Cancel is accepted and a later status remains readable.", ["not currently indexing", "during indexing"], ["index-paused"], commonEvidence, "chipmate.codeGraph.cancel"),
  c("codegraph.empty", "codegraph", "Empty workspace does not crash CodeGraph", "P1", "automated", ["cloned-profile-full"], ["fixture:empty"], "Index an empty fixture workspace.", "The result is ready/empty or an explicit unsupported-workspace reason.", ["no files", "no git"], ["workspace-unsupported"], ["logs/", "codegraph-summary.json"], "chipmate.codeGraph.index", "empty"),
  c("codegraph.large", "codegraph", "Large fixture records bounded progress", "P2", "planned", ["cloned-profile-full"], ["fixture:large-index"], "Index a larger fixture.", "Progress, limits, and save phases are observable.", ["maxFiles", "sharded storage"], ["index-paused", "timeout"], ["logs/", "codegraph-summary.json"]),
  c("codegraph.build-churn", "codegraph", "Build output churn does not cause misleading RAG restart diagnosis", "P1", "planned", ["cloned-profile-full"], ["fixture:build-churn"], "Generate build-like files while indexing.", "Invalidation, checkpoint, and resume status are distinguishable.", ["excludeGlobs", "watcher churn"], ["index-stale", "timeout"], ["logs/", "rag-summary.json", "codegraph-summary.json"]),
  c("codegraph.corrupt-storage", "codegraph", "Corrupt stored index falls back safely", "P1", "planned", ["cloned-profile-full"], ["fixture:corrupt-storage"], "Seed corrupted CodeGraph storage and activate.", "Extension reports stored-index-unavailable/rebuild-required instead of crashing.", ["bad manifest", "old schema"], ["index-stale"], ["logs/", "globalStorage-summary.json"]),
  c("codegraph.settings", "codegraph", "CodeGraph settings are covered by boundary cases", "P1", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.codeGraph.", "setting-prefix:chipmate.analysis."], "Vary CodeGraph and analysis limits, paths, exclusions, and worker settings.", "Indexing/query behavior remains bounded and reports clear configuration or storage state.", ["maxFiles", "excludeGlobs", "workerConcurrency", "compile command paths"], ["configuration-error", "index-stale", "workspace-unsupported"], ["logs/", "codegraph-summary.json"]),
  c("rag.status", "code-rag", "RAG status is included in CodeGraph status", "P1", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.codeGraph.status"], "Collect CodeGraph status and storage summary.", "RAG state is summarized as unavailable/not-indexed/indexing/ready/etc.", ["no endpoint", "ready index"], ["configuration-error", "provider-error"], ["logs/", "rag-summary.json"], "chipmate.codeGraph.status"),
  c("rag.test-vs-resume", "code-rag", "RAG Test and Resume semantics stay separate", "P1", "planned", ["cloned-profile-full"], ["webview:rag-settings"], "Run Test and Resume from RAG settings.", "Test only probes connectivity; Resume recovers or refreshes index status.", ["provider-error", "partial index"], ["provider-error", "index-stale"], commonEvidence),
  c("rag.identity-change", "code-rag", "Embedding identity change requires rebuild confirmation", "P1", "planned", ["cloned-profile-full"], ["setting:chipmate.rag.embedding.endpoint", "setting:chipmate.rag.embedding.model"], "Change embedding endpoint/model and save.", "UI explains rebuild requirement and does not silently reuse old vectors.", ["old ready index", "partial index"], ["configuration-error"], commonEvidence),
  c("rag.scheduler-change", "code-rag", "Scheduler changes preserve partial work", "P2", "planned", ["cloned-profile-full"], ["setting:chipmate.rag.embedding.batchSize", "setting:chipmate.rag.embedding.concurrentRequests"], "Change batch/concurrency settings during partial indexing.", "Partial work is preserved or resumed with clear status.", ["rate limit", "request budget"], ["provider-error", "index-paused"], ["logs/", "rag-summary.json"]),
  c("rag.query-change", "code-rag", "Rerank/query-only changes avoid forced rebuild", "P2", "planned", ["cloned-profile-full"], ["setting:chipmate.rag.rerank.endpoint", "setting:chipmate.rag.vectorTopK"], "Change rerank/query settings.", "Index is not deleted and status refreshes clearly.", ["rerank unavailable", "vectorTopK zero"], ["provider-error"], ["logs/", "rag-summary.json"]),
  c("rag.rate-limit-timeout", "code-rag", "RAG rate limit and timeout are classified", "P1", "planned", ["cloned-profile-full"], ["mock:embedding-provider"], "Mock 429/503/timeouts during embedding.", "Paused/partial status includes retry and request budget evidence.", ["retry-after", "timeout"], ["rate-limit", "provider-error"], ["logs/", "rag-summary.json"]),
  c("rag.settings", "code-rag", "All RAG settings are covered by lifecycle cases", "P1", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.rag."], "Vary embedding, rerank, allowed-host, index-tests, topK, checkpoint, retry, timeout, and resume settings.", "Settings map to identity/scheduler/query policy and status remains explainable.", ["identity change", "scheduler change", "query-only change", "invalid host"], ["configuration-error", "provider-error", "index-stale"], ["logs/", "rag-summary.json"]),
  c("document-rag.status", "document-rag", "Document RAG status command works", "P2", "automated", ["real-profile-observe", "cloned-profile-full"], ["command:chipmate.documentRag.status"], "Run Show Document RAG Status.", "Command is accepted and logs are collected.", ["not indexed", "disabled"], ["workspace-unsupported"], commonEvidence, "chipmate.documentRag.status"),
  c("document-rag.rebuild", "document-rag", "Document RAG rebuild handles document fixture", "P2", "automated", ["cloned-profile-full"], ["command:chipmate.documentRag.rebuild"], "Run Rebuild Document RAG.", "Reconcile/index/skipped/failure evidence is collected.", ["empty document", "markdown", "txt"], ["workspace-unsupported", "runtime-missing"], ["logs/", "globalStorage-summary.json"], "chipmate.documentRag.rebuild", "documents"),
  c("document-rag.pause-resume", "document-rag", "Document RAG pause and resume are stable", "P2", "automated", ["cloned-profile-full"], ["command:chipmate.documentRag.pause", "command:chipmate.documentRag.resume"], "Pause then resume Document RAG.", "Commands are accepted without extension-host crash.", ["already paused", "not indexing"], ["index-paused"], commonEvidence, "chipmate.documentRag.pause"),
  c("document-rag.settings", "document-rag", "Document RAG settings are covered by document fixtures", "P2", "planned", ["cloned-profile-full"], ["setting-prefix:chipmate.documentRag."], "Vary Document RAG file limits, extraction limits, exclusions, topK, evidence bytes, and workers.", "Document indexing remains bounded and errors identify parser/config/runtime layer.", ["large docs", "excludeGlobs", "workerConcurrency"], ["configuration-error", "runtime-missing", "workspace-unsupported"], ["logs/", "globalStorage-summary.json"]),
  c("documents.word-read", "documents", "Word read/edit tools handle valid and corrupt files", "P1", "planned", ["cloned-profile-full"], ["tool:readDocx", "tool:createWordDocument"], "Ask ChipMate to read/edit fixture documents.", "Valid documents succeed; corrupt/unsupported files produce field-level error summaries.", ["doc", "docx", "corrupt file", "file locked"], ["runtime-missing", "validation-error"], commonEvidence),
  c("documents.render-gate", "documents", "Word render quality gate reports failures", "P1", "planned", ["cloned-profile-full"], ["tool:word-render"], "Generate a document and run render quality checks.", "Render failures have actionable summaries and do not dump full content.", ["large table", "style preservation"], ["runtime-missing", "validation-error"], commonEvidence),
  c("comments.current-function", "comments", "Generate comments for current function", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.comments.generateForCurrentFunction"], "Open C fixture and run current-function comments.", "Comment pipeline starts or reports clear provider/unsupported reason.", ["provider unavailable", "unsupported language"], ["provider-error", "workspace-unsupported"], ["logs/chipmate-comment-output.log", "screenshots/"], "chipmate.comments.generateForCurrentFunction", "small-c"),
  c("comments.selection", "comments", "Generate comments for selection", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.comments.generateForSelection"], "Select code and run selection comments.", "Comment pipeline starts or reports clear selection/provider reason.", ["empty selection", "large selection"], ["provider-error", "workspace-unsupported"], ["logs/chipmate-comment-output.log", "screenshots/"], "chipmate.comments.generateForSelection", "small-c"),
  c("comments.workspace-changes", "comments", "Generate comments for workspace changes", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.comments.generateForWorkspaceChanges"], "Open SCM fixture with changes and run workspace comments.", "Workspace scan/generation path starts or gives clear no-changes/provider reason.", ["no changes", "large diff"], ["provider-error", "workspace-unsupported"], ["logs/chipmate-comment-output.log"], "chipmate.comments.generateForWorkspaceChanges", "scm-changes"),
  c("comments.review-actions", "comments", "Accept/reject/clear comment proposals", "P2", "automated", ["cloned-profile-full"], ["command:chipmate.comments.accept", "command:chipmate.comments.acceptAll", "command:chipmate.comments.reject", "command:chipmate.comments.clear"], "Run proposal review commands with no/possible proposal.", "Commands do not crash and empty-state messages are clear.", ["no proposal", "stale proposal"], ["ui-automation-failure"], commonEvidence, "chipmate.comments.clear"),
  c("terminal.open", "agent-terminal", "Agent terminal opens", "P1", "automated", ["cloned-profile-full"], ["command:chipmate.agentTerminal.open"], "Run Open ChipMate Agent Terminal.", "Terminal UI opens or logs a clear failure.", ["no workspace", "restricted shell"], ["ui-automation-failure"], commonEvidence, "chipmate.agentTerminal.open"),
  c("tools.command-success", "tools", "Tool command success is reported", "P2", "planned", ["cloned-profile-full"], ["tool:exec_command"], "Ask agent terminal to run a safe read-only command.", "stdout/status are bounded and reported.", ["large output", "cwd with spaces"], ["tool-error"], commonEvidence),
  c("tools.command-errors", "tools", "Tool command failures are bounded", "P1", "planned", ["cloned-profile-full"], ["tool:exec_command"], "Run timeout, stderr, and non-zero commands.", "Errors are classified without hanging the extension.", ["timeout", "large stderr", "non-zero exit"], ["tool-error", "timeout"], commonEvidence),
  c("skills.list", "skills", "Skills and missing dependencies are diagnosable", "P2", "planned", ["cloned-profile-full"], ["tool:skills"], "Ask ChipMate to use/list skills.", "Missing dependency and permission failures have clear diagnostics.", ["missing skill", "bad manifest"], ["runtime-missing", "tool-error"], commonEvidence),
  c("diagram.mermaid", "diagram", "Mermaid rendering path is observable", "P2", "planned", ["cloned-profile-full"], ["feature:mermaid"], "Ask for a Mermaid diagram.", "Preview/export succeeds or gives render-specific error.", ["complex graph", "invalid syntax"], ["render-error"], commonEvidence),
  c("diagram.drawio", "diagram", "draw.io rendering and PNG export are observable", "P2", "planned", ["cloned-profile-full"], ["feature:drawio"], "Ask for draw.io/PNG output.", "Layout/render errors are explicit and original answer is preserved.", ["invalid style", "large graph"], ["render-error", "runtime-missing"], commonEvidence),
  c("ui.theme-dark-light", "ui", "Core UI works in dark and light themes", "P2", "planned", ["cloned-profile-full"], ["setting:workbench.colorTheme"], "Run smoke in dark and light themes.", "Buttons, icons, loading, and errors remain visible.", ["narrow window", "high contrast"], ["ui-automation-failure"], ["screenshots/", "summary.json"]),
  c("ui.narrow-window", "ui", "Narrow window does not overlap controls", "P2", "planned", ["cloned-profile-full"], ["webview:layout"], "Resize VS Code to a narrow width and open major panels.", "Text/buttons/icons do not overlap or overflow.", ["small width", "long labels"], ["ui-overlap"], ["screenshots/"]),
  c("ui.accessibility", "ui", "Icon buttons are labeled", "P2", "planned", ["cloned-profile-full"], ["webview:aria"], "Inspect key webview controls.", "Icon buttons have tooltip/aria labels and disabled/loading states.", ["keyboard only", "screen reader mode"], ["accessibility-gap"], ["screenshots/"]),
  c("lifecycle.clean-install", "lifecycle", "Clean profile first-run is usable", "P0", "automated", ["fixture-clean-room"], ["mode:fixture-clean-room"], "Launch VS Code with an empty user-data-dir and installed extension dir.", "Extension activates without assuming existing globalStorage.", ["no settings", "no SecretStorage"], ["configuration-error", "extension-host-error"], commonEvidence, "chipmate.openChat"),
  c("lifecycle.upgrade-storage", "lifecycle", "Old storage does not block startup", "P1", "planned", ["cloned-profile-full"], ["fixture:corrupt-storage"], "Seed old/corrupt storage and activate.", "Extension falls back to rebuild-required instead of crashing.", ["old manifest", "bad JSON"], ["index-stale"], ["logs/", "globalStorage-summary.json"]),
  c("offline.no-network", "offline", "No network failures are classified", "P1", "planned", ["cloned-profile-full"], ["network:offline"], "Run provider-backed flows with network blocked.", "Errors are provider/transport-specific and UI remains usable.", ["DNS failure", "proxy failure"], ["transport-error"], commonEvidence),
  c("offline.runtime-deps", "offline", "Packaged runtime dependencies are present", "P0", "observe", ["real-profile-observe", "cloned-profile-full"], ["logs:runtime"], "Scan logs for missing runtime dependency markers.", "No missing module/wasm/runtime download marker appears.", ["fresh install", "offline mode"], ["runtime-missing"], ["logs/"]),
  c("security.redaction", "security", "Reports redact secrets", "P0", "observe", ["real-profile-observe", "cloned-profile-full", "fixture-clean-room"], ["report:redaction"], "Scan generated reports for token-shaped secrets and configured sensitive values.", "Reports contain no API keys, bearer tokens, or raw user secrets.", ["provider configured", "error includes headers"], ["secret-leak"], ["redaction-report.json"]),
  c("completion.disabled-boundary", "completion-boundary", "Completion quality is excluded but does not affect other tests", "P2", "observe", ["real-profile-observe", "cloned-profile-full"], ["setting-prefix:chipmate.completion.", "command:chipmate.qwenAutocomplete.regenerate", "command:chipmate.qwenAutocomplete.showLogs", "command:chipmate.qwenAutocomplete.exportDiagnostics"], "Record completion setting and keep system cases focused elsewhere.", "Completion is not quality-tested and no inline suggestion oracle is used.", ["completion enabled in real profile", "inherit chat settings"], ["configuration-error"], ["environment.json"]),
]

function c(
  id: string,
  area: string,
  title: string,
  severity: Severity,
  automation: AutomationKind,
  modes: RunMode[],
  entrypoints: string[],
  userAction: string,
  expected: string,
  boundaries: string[],
  allowedFailures: string[],
  evidence: string[],
  commandId?: string,
  fixture?: string,
  destructive?: boolean,
): SystemCase {
  return {
    id,
    area,
    title,
    severity,
    automation,
    modes,
    entrypoints,
    userAction,
    expected,
    boundaries,
    allowedFailures,
    evidence,
    commandId,
    fixture,
    destructive,
  }
}
